//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.SaaS.BLLCommonServices.PublicInterfaceWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.PublicInterface.BLL")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POSTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANYID {
            get {
                return this.COMPANYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYIDField, value) != true)) {
                    this.COMPANYIDField = value;
                    this.RaisePropertyChanged("COMPANYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTMENTID {
            get {
                return this.DEPARTMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTMENTIDField, value) != true)) {
                    this.DEPARTMENTIDField = value;
                    this.RaisePropertyChanged("DEPARTMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POSTID {
            get {
                return this.POSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.POSTIDField, value) != true)) {
                    this.POSTIDField = value;
                    this.RaisePropertyChanged("POSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERID {
            get {
                return this.USERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.USERIDField, value) != true)) {
                    this.USERIDField = value;
                    this.RaisePropertyChanged("USERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublicInterfaceWS.IPublicService")]
    public interface IPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetBusinessObject", ReplyAction="http://tempuri.org/IPublicService/GetBusinessObjectResponse")]
        string GetBusinessObject(string SystemCode, string BusinessObjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetContent", ReplyAction="http://tempuri.org/IPublicService/GetContentResponse")]
        byte[] GetContent(string FORMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetContentFormatImgToUrl", ReplyAction="http://tempuri.org/IPublicService/GetContentFormatImgToUrlResponse")]
        string GetContentFormatImgToUrl(string FORMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/DeleteContent", ReplyAction="http://tempuri.org/IPublicService/DeleteContentResponse")]
        bool DeleteContent(string FORMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/UpdateContent", ReplyAction="http://tempuri.org/IPublicService/UpdateContentResponse")]
        bool UpdateContent(string FormID, byte[] content, SMT.SaaS.BLLCommonServices.PublicInterfaceWS.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/AddContent", ReplyAction="http://tempuri.org/IPublicService/AddContentResponse")]
        bool AddContent(string FormID, byte[] content, string CompanyID, string SystemCode, string ModelName, SMT.SaaS.BLLCommonServices.PublicInterfaceWS.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/IsExits", ReplyAction="http://tempuri.org/IPublicService/IsExitsResponse")]
        bool IsExits(string FORMID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicServiceChannel : SMT.SaaS.BLLCommonServices.PublicInterfaceWS.IPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicServiceClient : System.ServiceModel.ClientBase<SMT.SaaS.BLLCommonServices.PublicInterfaceWS.IPublicService>, SMT.SaaS.BLLCommonServices.PublicInterfaceWS.IPublicService {
        
        public PublicServiceClient() {
        }
        
        public PublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBusinessObject(string SystemCode, string BusinessObjectName) {
            return base.Channel.GetBusinessObject(SystemCode, BusinessObjectName);
        }
        
        public byte[] GetContent(string FORMID) {
            return base.Channel.GetContent(FORMID);
        }
        
        public string GetContentFormatImgToUrl(string FORMID) {
            return base.Channel.GetContentFormatImgToUrl(FORMID);
        }
        
        public bool DeleteContent(string FORMID) {
            return base.Channel.DeleteContent(FORMID);
        }
        
        public bool UpdateContent(string FormID, byte[] content, SMT.SaaS.BLLCommonServices.PublicInterfaceWS.UserInfo userinfo) {
            return base.Channel.UpdateContent(FormID, content, userinfo);
        }
        
        public bool AddContent(string FormID, byte[] content, string CompanyID, string SystemCode, string ModelName, SMT.SaaS.BLLCommonServices.PublicInterfaceWS.UserInfo userinfo) {
            return base.Channel.AddContent(FormID, content, CompanyID, SystemCode, ModelName, userinfo);
        }
        
        public bool IsExits(string FORMID) {
            return base.Channel.IsExits(FORMID);
        }
    }
}
