//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.SaaS.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMT.SaaS.Globalization.LMResource", typeof(LMResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 受理 的本地化字符串。
        /// </summary>
        internal static string ACCEPT {
            get {
                return ResourceManager.GetString("ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受理部门 的本地化字符串。
        /// </summary>
        internal static string ACCEPTDEPARTMENT {
            get {
                return ResourceManager.GetString("ACCEPTDEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已受理 的本地化字符串。
        /// </summary>
        internal static string ACCEPTED {
            get {
                return ResourceManager.GetString("ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单处理 的本地化字符串。
        /// </summary>
        internal static string ACCEPTORDERLIST {
            get {
                return ResourceManager.GetString("ACCEPTORDERLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受理机构 的本地化字符串。
        /// </summary>
        internal static string ACCEPTORG {
            get {
                return ResourceManager.GetString("ACCEPTORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时效警戒 的本地化字符串。
        /// </summary>
        internal static string AGINGALERT {
            get {
                return ResourceManager.GetString("AGINGALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驳回 的本地化字符串。
        /// </summary>
        internal static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回退成功 的本地化字符串。
        /// </summary>
        internal static string BACKSUCCESSED {
            get {
                return ResourceManager.GetString("BACKSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string CANCELLATION {
            get {
                return ResourceManager.GetString("CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销成功 的本地化字符串。
        /// </summary>
        internal static string CANCELLATIONSUCCESSED {
            get {
                return ResourceManager.GetString("CANCELLATIONSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能删除未提交和审核未通过的记录 的本地化字符串。
        /// </summary>
        internal static string CANDELETENOTAUDITORNOTPASS {
            get {
                return ResourceManager.GetString("CANDELETENOTAUDITORNOTPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此{0}已添加，请不要重复! 的本地化字符串。
        /// </summary>
        internal static string CANNOTREPEAT {
            get {
                return ResourceManager.GetString("CANNOTREPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执机构 的本地化字符串。
        /// </summary>
        internal static string CARRYCOMPANYID {
            get {
                return ResourceManager.GetString("CARRYCOMPANYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执人 的本地化字符串。
        /// </summary>
        internal static string CARRYOPERATORID {
            get {
                return ResourceManager.GetString("CARRYOPERATORID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执 的本地化字符串。
        /// </summary>
        internal static string CARRYSIGN {
            get {
                return ResourceManager.GetString("CARRYSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单时间 的本地化字符串。
        /// </summary>
        internal static string CARRYSIGNDATE {
            get {
                return ResourceManager.GetString("CARRYSIGNDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执记录 的本地化字符串。
        /// </summary>
        internal static string CARRYSIGNDETIL {
            get {
                return ResourceManager.GetString("CARRYSIGNDETIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执状态 的本地化字符串。
        /// </summary>
        internal static string CARRYSIGNSTATE {
            get {
                return ResourceManager.GetString("CARRYSIGNSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执类型 的本地化字符串。
        /// </summary>
        internal static string CARRYTYPE {
            get {
                return ResourceManager.GetString("CARRYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        internal static string CLASS {
            get {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司编号 的本地化字符串。
        /// </summary>
        internal static string COMPANYCODE {
            get {
                return ResourceManager.GetString("COMPANYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉内容描述 的本地化字符串。
        /// </summary>
        internal static string COMPLAINTCONTENT {
            get {
                return ResourceManager.GetString("COMPLAINTCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉客户 的本地化字符串。
        /// </summary>
        internal static string COMPLAINTCUSTOMER {
            get {
                return ResourceManager.GetString("COMPLAINTCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉日期 的本地化字符串。
        /// </summary>
        internal static string COMPLAINTDATE {
            get {
                return ResourceManager.GetString("COMPLAINTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被投诉机构 的本地化字符串。
        /// </summary>
        internal static string COMPLAINTORGANIZATIONS {
            get {
                return ResourceManager.GetString("COMPLAINTORGANIZATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收发人ID 的本地化字符串。
        /// </summary>
        internal static string COPERATORID {
            get {
                return ResourceManager.GetString("COPERATORID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常用报价因素 的本地化字符串。
        /// </summary>
        internal static string CUSTOMERFACTOR {
            get {
                return ResourceManager.GetString("CUSTOMERFACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户不存在 的本地化字符串。
        /// </summary>
        internal static string CUSTOMERSDONOTEXIST {
            get {
                return ResourceManager.GetString("CUSTOMERSDONOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 派件人 的本地化字符串。
        /// </summary>
        internal static string DELIVER {
            get {
                return ResourceManager.GetString("DELIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 派件人代码 的本地化字符串。
        /// </summary>
        internal static string DELIVERCODE {
            get {
                return ResourceManager.GetString("DELIVERCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货时效 的本地化字符串。
        /// </summary>
        internal static string DELIVERYLIMITATION {
            get {
                return ResourceManager.GetString("DELIVERYLIMITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在，请重新选择！ 的本地化字符串。
        /// </summary>
        internal static string DOESNOTEXISTENTERAGAIN {
            get {
                return ResourceManager.GetString("DOESNOTEXISTENTERAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此货物已添加,请不要重复! 的本地化字符串。
        /// </summary>
        internal static string DONOTREPEAT {
            get {
                return ResourceManager.GetString("DONOTREPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价因素 的本地化字符串。
        /// </summary>
        internal static string FACTOR {
            get {
                return ResourceManager.GetString("FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 因素名称 的本地化字符串。
        /// </summary>
        internal static string FACTORNAME {
            get {
                return ResourceManager.GetString("FACTORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货重 的本地化字符串。
        /// </summary>
        internal static string GOODSHEAVY {
            get {
                return ResourceManager.GetString("GOODSHEAVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此货品信息不存在 的本地化字符串。
        /// </summary>
        internal static string GOODSNOTEXIST {
            get {
                return ResourceManager.GetString("GOODSNOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货数量 的本地化字符串。
        /// </summary>
        internal static string huo {
            get {
                return ResourceManager.GetString("huo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单号 的本地化字符串。
        /// </summary>
        internal static string INPUTCODE {
            get {
                return ResourceManager.GetString("INPUTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉核查员 的本地化字符串。
        /// </summary>
        internal static string INSPECTORS {
            get {
                return ResourceManager.GetString("INSPECTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代收货款 的本地化字符串。
        /// </summary>
        internal static string ISINSTEADGET {
            get {
                return ResourceManager.GetString("ISINSTEADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否代理签收 的本地化字符串。
        /// </summary>
        internal static string ISPROXY {
            get {
                return ResourceManager.GetString("ISPROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物数量 的本地化字符串。
        /// </summary>
        internal static string MOVEQTYSUM {
            get {
                return ResourceManager.GetString("MOVEQTYSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为正整数 的本地化字符串。
        /// </summary>
        internal static string MUSTINT {
            get {
                return ResourceManager.GetString("MUSTINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执记录已存在 的本地化字符串。
        /// </summary>
        internal static string NOCARRYSIGN {
            get {
                return ResourceManager.GetString("NOCARRYSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执记录详细已添加，直接查看 的本地化字符串。
        /// </summary>
        internal static string NOCARRYSIGNDETAIL {
            get {
                return ResourceManager.GetString("NOCARRYSIGNDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能选取中国进行添加 的本地化字符串。
        /// </summary>
        internal static string NOCHINA {
            get {
                return ResourceManager.GetString("NOCHINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网点机构 的本地化字符串。
        /// </summary>
        internal static string NODEORG {
            get {
                return ResourceManager.GetString("NODEORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准时效 的本地化字符串。
        /// </summary>
        internal static string NORMALTIMELINESS {
            get {
                return ResourceManager.GetString("NORMALTIMELINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未受理 的本地化字符串。
        /// </summary>
        internal static string NOTACCEPT {
            get {
                return ResourceManager.GetString("NOTACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能修改未提交和审核未通过的记录! 的本地化字符串。
        /// </summary>
        internal static string NOTAUDITORNOTPASS {
            get {
                return ResourceManager.GetString("NOTAUDITORNOTPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在 的本地化字符串。
        /// </summary>
        internal static string NOTEXIST {
            get {
                return ResourceManager.GetString("NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空,并且是整数 的本地化字符串。
        /// </summary>
        internal static string NOTNULLANDISINT {
            get {
                return ResourceManager.GetString("NOTNULLANDISINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有此行政区域 的本地化字符串。
        /// </summary>
        internal static string NOTTHISUALSCXGA {
            get {
                return ResourceManager.GetString("NOTTHISUALSCXGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收发机构ID 的本地化字符串。
        /// </summary>
        internal static string OPCOMPANYID {
            get {
                return ResourceManager.GetString("OPCOMPANYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收发机构名称 的本地化字符串。
        /// </summary>
        internal static string OPCOMPANYNAME {
            get {
                return ResourceManager.GetString("OPCOMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收发时间 的本地化字符串。
        /// </summary>
        internal static string OPDATE {
            get {
                return ResourceManager.GetString("OPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行状态 的本地化字符串。
        /// </summary>
        internal static string OPERATIONSTATE {
            get {
                return ResourceManager.GetString("OPERATIONSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收发人名称 的本地化字符串。
        /// </summary>
        internal static string OPERATORNAME {
            get {
                return ResourceManager.GetString("OPERATORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单单号 的本地化字符串。
        /// </summary>
        internal static string ORDERCODE {
            get {
                return ResourceManager.GetString("ORDERCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货订单 的本地化字符串。
        /// </summary>
        internal static string ORDERDELIVERYLIST {
            get {
                return ResourceManager.GetString("ORDERDELIVERYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 派送订单 的本地化字符串。
        /// </summary>
        internal static string ORDERDISPATCHLIST {
            get {
                return ResourceManager.GetString("ORDERDISPATCHLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单录入 的本地化字符串。
        /// </summary>
        internal static string ORDERFORMMANAGE {
            get {
                return ResourceManager.GetString("ORDERFORMMANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点订单 的本地化字符串。
        /// </summary>
        internal static string ORDERINVENTORYLIST {
            get {
                return ResourceManager.GetString("ORDERINVENTORYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工订单 的本地化字符串。
        /// </summary>
        internal static string ORDERPROCESSINGLIST {
            get {
                return ResourceManager.GetString("ORDERPROCESSINGLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退库订单 的本地化字符串。
        /// </summary>
        internal static string ORDERRETURNLIST {
            get {
                return ResourceManager.GetString("ORDERRETURNLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库订单 的本地化字符串。
        /// </summary>
        internal static string ORDERSTORAGELIST {
            get {
                return ResourceManager.GetString("ORDERSTORAGELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空，请首先选择网点！ 的本地化字符串。
        /// </summary>
        internal static string ORGTONODE {
            get {
                return ResourceManager.GetString("ORGTONODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库单号 的本地化字符串。
        /// </summary>
        internal static string OUTSTOCKCODE {
            get {
                return ResourceManager.GetString("OUTSTOCKCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级客户 的本地化字符串。
        /// </summary>
        internal static string PARENTCUSTOMER {
            get {
                return ResourceManager.GetString("PARENTCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员分类 的本地化字符串。
        /// </summary>
        internal static string PERSONNELCLASS {
            get {
                return ResourceManager.GetString("PERSONNELCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员类型 的本地化字符串。
        /// </summary>
        internal static string PERSONNELTYPE {
            get {
                return ResourceManager.GetString("PERSONNELTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拣货单号 的本地化字符串。
        /// </summary>
        internal static string PICKCODE {
            get {
                return ResourceManager.GetString("PICKCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处罚情况 的本地化字符串。
        /// </summary>
        internal static string PUNISHMENTS {
            get {
                return ResourceManager.GetString("PUNISHMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上架单号 的本地化字符串。
        /// </summary>
        internal static string PUTUPCODE {
            get {
                return ResourceManager.GetString("PUTUPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收数 的本地化字符串。
        /// </summary>
        internal static string REALQTY {
            get {
                return ResourceManager.GetString("REALQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执单号 的本地化字符串。
        /// </summary>
        internal static string RECEIPTCODE {
            get {
                return ResourceManager.GetString("RECEIPTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执描述 的本地化字符串。
        /// </summary>
        internal static string RECEIPTDESCRIBE {
            get {
                return ResourceManager.GetString("RECEIPTDESCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单号 的本地化字符串。
        /// </summary>
        internal static string RECEIVEGOODSCODE {
            get {
                return ResourceManager.GetString("RECEIVEGOODSCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人ID 的本地化字符串。
        /// </summary>
        internal static string RECEIVEID {
            get {
                return ResourceManager.GetString("RECEIVEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人姓名 的本地化字符串。
        /// </summary>
        internal static string RECEIVENAME {
            get {
                return ResourceManager.GetString("RECEIVENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执要求 的本地化字符串。
        /// </summary>
        internal static string REQUEST {
            get {
                return ResourceManager.GetString("REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任岗位 的本地化字符串。
        /// </summary>
        internal static string RESPONSEPOST {
            get {
                return ResourceManager.GetString("RESPONSEPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退货订单 的本地化字符串。
        /// </summary>
        internal static string RETURNORDERLIST {
            get {
                return ResourceManager.GetString("RETURNORDERLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已回复 的本地化字符串。
        /// </summary>
        internal static string REVERTED {
            get {
                return ResourceManager.GetString("REVERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复时间 的本地化字符串。
        /// </summary>
        internal static string REVERTTIME {
            get {
                return ResourceManager.GetString("REVERTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复时间必须大于投诉时间 的本地化字符串。
        /// </summary>
        internal static string REVERTTIMEBIGGERCOMPLAINTDATE {
            get {
                return ResourceManager.GetString("REVERTTIMEBIGGERCOMPLAINTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义编码 的本地化字符串。
        /// </summary>
        internal static string SELFDEFINECODE {
            get {
                return ResourceManager.GetString("SELFDEFINECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回执时间 的本地化字符串。
        /// </summary>
        internal static string SENDRECIVEDATE {
            get {
                return ResourceManager.GetString("SENDRECIVEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务服务内容 的本地化字符串。
        /// </summary>
        internal static string SERVICECONTENT {
            get {
                return ResourceManager.GetString("SERVICECONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收日期 的本地化字符串。
        /// </summary>
        internal static string SIGNDATE {
            get {
                return ResourceManager.GetString("SIGNDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收人姓名 的本地化字符串。
        /// </summary>
        internal static string SIGNER {
            get {
                return ResourceManager.GetString("SIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收时间 的本地化字符串。
        /// </summary>
        internal static string SIGNTIME {
            get {
                return ResourceManager.GetString("SIGNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单重(KG) 的本地化字符串。
        /// </summary>
        internal static string SINGLEWEIGHT {
            get {
                return ResourceManager.GetString("SINGLEWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货源客户 的本地化字符串。
        /// </summary>
        internal static string SOURCECUSTOMER {
            get {
                return ResourceManager.GetString("SOURCECUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音编码 的本地化字符串。
        /// </summary>
        internal static string SPELLCODE {
            get {
                return ResourceManager.GetString("SPELLCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点单号 的本地化字符串。
        /// </summary>
        internal static string STOCKCOUNTCODE {
            get {
                return ResourceManager.GetString("STOCKCOUNTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已提交 的本地化字符串。
        /// </summary>
        internal static string SUBMITED {
            get {
                return ResourceManager.GetString("SUBMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行政区域 的本地化字符串。
        /// </summary>
        internal static string UALSCXGA {
            get {
                return ResourceManager.GetString("UALSCXGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string UPDATEPASSWORD {
            get {
                return ResourceManager.GetString("UPDATEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入... 的本地化字符串。
        /// </summary>
        internal static string WatermarkedTextBox_DefaultWatermarkText {
            get {
                return ResourceManager.GetString("WatermarkedTextBox_DefaultWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板部分是不正确的类型。 的本地化字符串。
        /// </summary>
        internal static string WatermarkedTextBox_TemplatePartIsOfIncorrectType {
            get {
                return ResourceManager.GetString("WatermarkedTextBox_TemplatePartIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五笔编码 的本地化字符串。
        /// </summary>
        internal static string WBXCODE {
            get {
                return ResourceManager.GetString("WBXCODE", resourceCulture);
            }
        }
    }
}
