/*==============================================================*/
/* DBMS name:      ORACLE Version 10g                           */
/* Created on:     2010/12/4 9:56:35                            */
/*==============================================================*/


ALTER TABLE "T_OA_AREAALLOWANCE"
   DROP CONSTRAINT "FK_AREADIFFERENCE_T_OA_ARE";

ALTER TABLE "T_OA_AREACITY"
   DROP CONSTRAINT "FK_T_OA_ARE_AREACITY";

ALTER TABLE T_OA_BUSINESSREPORT
   DROP CONSTRAINT FK_BUSINESSTRIP_T_OA_BUS;

ALTER TABLE T_OA_BUSINESSREPORTDETAIL
   DROP CONSTRAINT FK_T_OA_REPORTDETAIL_T_OA_BUS;

ALTER TABLE T_OA_BUSINESSTRIPDETAIL
   DROP CONSTRAINT FK_T_OA_BUS_T_OA_BUSDETAIL;

ALTER TABLE T_OA_CANTAKETHEPLANELINE
   DROP CONSTRAINT FK_T_OA_CAN_REFERENCE_T_OA_TRA;

ALTER TABLE T_OA_PROGRAMAPPLICATIONS
   DROP CONSTRAINT FK_T_OA_PRO_REFERENCE_T_OA_TRA;

ALTER TABLE T_OA_REIMBURSEMENTDETAIL
   DROP CONSTRAINT FK_T_OA_REI_REFERENCE_T_OA_TRA;

ALTER TABLE T_OA_TAKETHESTANDARDTRANSPORT
   DROP CONSTRAINT FK_T_OA_TAK_REFERENCE_T_OA_TRA;

ALTER TABLE T_OA_TRAVELREIMBURSEMENT
   DROP CONSTRAINT FK_T_OA_TRA_REFERENCE_T_OA_BUS;

DROP TABLE "T_OA_AREAALLOWANCE" CASCADE CONSTRAINTS;

DROP TABLE "T_OA_AREACITY" CASCADE CONSTRAINTS;

DROP TABLE "T_OA_AREADIFFERENCE" CASCADE CONSTRAINTS;

DROP TABLE T_OA_BUSINESSREPORT CASCADE CONSTRAINTS;

DROP TABLE T_OA_BUSINESSREPORTDETAIL CASCADE CONSTRAINTS;

DROP TABLE T_OA_BUSINESSTRIP CASCADE CONSTRAINTS;

DROP TABLE T_OA_BUSINESSTRIPDETAIL CASCADE CONSTRAINTS;

DROP TABLE T_OA_CANTAKETHEPLANELINE CASCADE CONSTRAINTS;

DROP TABLE T_OA_PROGRAMAPPLICATIONS CASCADE CONSTRAINTS;

DROP TABLE T_OA_REIMBURSEMENTDETAIL CASCADE CONSTRAINTS;

DROP TABLE T_OA_TAKETHESTANDARDTRANSPORT CASCADE CONSTRAINTS;

DROP TABLE T_OA_TRAVELREIMBURSEMENT CASCADE CONSTRAINTS;

DROP TABLE T_OA_TRAVELSOLUTIONS CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: "T_OA_AREAALLOWANCE"                                  */
/*==============================================================*/
CREATE TABLE "T_OA_AREAALLOWANCE"  (
   "AREAALLOWANCEID"    NVARCHAR2(50)                   NOT NULL,
   "AREADIFFERENCEID"   NVARCHAR2(50),
   "POSTLEVEL"          NVARCHAR2(50),
   ACCOMMODATION        NUMBER,
   "TRANSPORTATIONSUBSIDIES" NUMBER,
   "MEALSUBSIDIES"      NUMBER,
   "OVERSEASSUBSIDIES"  NUMBER,
   "CREATEUSERID"       NVARCHAR2(50),
   "CREATEDATE"         DATE                           DEFAULT SYSDATE,
   "UPDATEUSERID"       NVARCHAR2(50),
   "UPDATEDATE"         DATE                           DEFAULT SYSDATE,
   CONSTRAINT PK_T_OA_AREAALLOWANCE PRIMARY KEY ("AREAALLOWANCEID")
);

COMMENT ON TABLE "T_OA_AREAALLOWANCE" IS
'地区差异补贴';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."AREAALLOWANCEID" IS
'地区补贴ID';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."AREADIFFERENCEID" IS
'地区分类ID';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."POSTLEVEL" IS
'岗位等级';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE".ACCOMMODATION IS
'住宿补贴费用';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."TRANSPORTATIONSUBSIDIES" IS
'交通补贴费用';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."MEALSUBSIDIES" IS
'餐费补贴';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."OVERSEASSUBSIDIES" IS
'驻外补贴标准';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."CREATEUSERID" IS
'创建人';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."CREATEDATE" IS
'创建时间';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."UPDATEUSERID" IS
'修改人';

COMMENT ON COLUMN "T_OA_AREAALLOWANCE"."UPDATEDATE" IS
'修改时间';

/*==============================================================*/
/* Table: "T_OA_AREACITY"                                       */
/*==============================================================*/
CREATE TABLE "T_OA_AREACITY"  (
   "AREACITYID"         NVARCHAR2(50)                   NOT NULL,
   "AREADIFFERENCEID"   NVARCHAR2(50),
   "CITY"               NVARCHAR2(10),
   "CREATEUSERID"       NVARCHAR2(50),
   "CREATEDATE"         DATE                           DEFAULT SYSDATE,
   "UPDATEUSERID"       NVARCHAR2(50),
   "UPDATEDATE"         DATE                           DEFAULT SYSDATE,
   CONSTRAINT PK_T_OA_AREACITY PRIMARY KEY ("AREACITYID")
);

COMMENT ON TABLE "T_OA_AREACITY" IS
'地区分类城市';

COMMENT ON COLUMN "T_OA_AREACITY"."AREACITYID" IS
'地区分类城市ID';

COMMENT ON COLUMN "T_OA_AREACITY"."AREADIFFERENCEID" IS
'地区分类ID';

COMMENT ON COLUMN "T_OA_AREACITY"."CITY" IS
'所在地城市，系统字典中定义';

COMMENT ON COLUMN "T_OA_AREACITY"."CREATEUSERID" IS
'创建人';

COMMENT ON COLUMN "T_OA_AREACITY"."CREATEDATE" IS
'创建时间';

COMMENT ON COLUMN "T_OA_AREACITY"."UPDATEUSERID" IS
'修改人';

COMMENT ON COLUMN "T_OA_AREACITY"."UPDATEDATE" IS
'修改时间';

/*==============================================================*/
/* Table: "T_OA_AREADIFFERENCE"                                 */
/*==============================================================*/
CREATE TABLE "T_OA_AREADIFFERENCE"  (
   "AREADIFFERENCEID"   NVARCHAR2(50)                   NOT NULL,
   "AREACATEGORY"       NVARCHAR2(50),
   "AREAINDEX"          NUMBER,
   "CREATEUSERID"       NVARCHAR2(50),
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATECOMPANYID      NVARCHAR2(50)                   NOT NULL,
   CREATEDEPARTMENTID   NVARCHAR2(50)                   NOT NULL,
   CREATEPOSTID         NVARCHAR2(50)                   NOT NULL,
   "CREATEDATE"         DATE                           DEFAULT SYSDATE,
   "UPDATEUSERID"       NVARCHAR2(50),
   "UPDATEUSERNAME"     NVARCHAR2(50),
   "UPDATEDATE"         DATE                           DEFAULT SYSDATE,
   "OWNERID"            NVARCHAR2(50),
   "OWNERPOSTID"        NVARCHAR2(50),
   "OWNERDEPARTMENTID"  NVARCHAR2(50),
   "OWNERCOMPANYID"     NVARCHAR2(50),
   CONSTRAINT PK_T_OA_AREADIFFERENCE PRIMARY KEY ("AREADIFFERENCEID")
);

COMMENT ON TABLE "T_OA_AREADIFFERENCE" IS
'地区差异分类表';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."AREADIFFERENCEID" IS
'地区分类ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."AREACATEGORY" IS
'地区分类名';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."AREAINDEX" IS
'地区分类序号';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."CREATEUSERID" IS
'创建人';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE".CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE".CREATECOMPANYID IS
'创建公司ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE".CREATEDEPARTMENTID IS
'创建部门ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE".CREATEPOSTID IS
'创建岗位ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."CREATEDATE" IS
'创建时间';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."UPDATEUSERID" IS
'修改人';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."UPDATEUSERNAME" IS
'修改人名';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."UPDATEDATE" IS
'修改时间';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."OWNERID" IS
'所属员工ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."OWNERPOSTID" IS
'所属岗位ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."OWNERDEPARTMENTID" IS
'所属部门ID';

COMMENT ON COLUMN "T_OA_AREADIFFERENCE"."OWNERCOMPANYID" IS
'所属公司ID';

/*==============================================================*/
/* Table: T_OA_BUSINESSREPORT                                   */
/*==============================================================*/
CREATE TABLE T_OA_BUSINESSREPORT  (
   BUSINESSREPORTID     NVARCHAR2(50)                   NOT NULL,
   BUSINESSTRIPID       NVARCHAR2(50),
   "TEL"                NVARCHAR2(50),
   CONTENT              VARCHAR2(2000)                  NOT NULL,
   CHECKSTATE           NVARCHAR2(1)                   DEFAULT '0' NOT NULL,
   "ISCHARGE"           NVARCHAR2(1)                   DEFAULT '0',
   "CHARGEMONEY"        NUMBER                         DEFAULT 0,
   REMARKS              NVARCHAR2(200),
   "OWNERID"            NVARCHAR2(50)                   NOT NULL,
   "OWNERNAME"          NVARCHAR2(50)                   NOT NULL,
   "OWNERCOMPANYID"     NVARCHAR2(50)                   NOT NULL,
   "OWNERDEPARTMENTID"  NVARCHAR2(50)                   NOT NULL,
   "OWNERPOSTID"        NVARCHAR2(50)                   NOT NULL,
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATECOMPANYID      NVARCHAR2(50)                   NOT NULL,
   CREATEDEPARTMENTID   NVARCHAR2(50)                   NOT NULL,
   CREATEPOSTID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   "UPDATEUSERNAME"     NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_BUSINESSREPORT PRIMARY KEY (BUSINESSREPORTID)
);

COMMENT ON TABLE T_OA_BUSINESSREPORT IS
'出差报告';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.BUSINESSREPORTID IS
'出差报告ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.BUSINESSTRIPID IS
'出差申请ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."TEL" IS
'联系电话';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CONTENT IS
'出差报告';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CHECKSTATE IS
'0：未提交；1：审核通过；2：审核中；3：审核未通过';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."ISCHARGE" IS
'0：无费用，1：有费用';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."CHARGEMONEY" IS
'报销总额';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.REMARKS IS
'备注';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."OWNERID" IS
'出差人';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."OWNERNAME" IS
'出差人名';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."OWNERCOMPANYID" IS
'所属公司';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."OWNERDEPARTMENTID" IS
'所属部门';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."OWNERPOSTID" IS
'所属岗位';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATECOMPANYID IS
'创建公司ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATEDEPARTMENTID IS
'创建部门ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATEPOSTID IS
'创建岗位ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_BUSINESSREPORT."UPDATEUSERNAME" IS
'修改人名';

COMMENT ON COLUMN T_OA_BUSINESSREPORT.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_BUSINESSREPORTDETAIL                             */
/*==============================================================*/
CREATE TABLE T_OA_BUSINESSREPORTDETAIL  (
   BUSINESSREPORTDETAILID NVARCHAR2(50)                   NOT NULL,
   BUSINESSREPORTID     NVARCHAR2(50)                   NOT NULL,
   STARTDATE            DATE                            NOT NULL,
   ENDDATE              DATE                            NOT NULL,
   "BUSINESSDAYS"       NVARCHAR2(50),
   "DEPCITY"            NVARCHAR2(50)                   NOT NULL,
   "DESTCITY"           NVARCHAR2(50)                   NOT NULL,
   CONSTRAINT PK_T_OA_BUSINESSREPORTDETAIL PRIMARY KEY (BUSINESSREPORTDETAILID)
);

COMMENT ON TABLE T_OA_BUSINESSREPORTDETAIL IS
'出差报告子表';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL.BUSINESSREPORTDETAILID IS
'报告子表ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL.BUSINESSREPORTID IS
'出差报告ID';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL.STARTDATE IS
'开始时间';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL.ENDDATE IS
'结束时间';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL."BUSINESSDAYS" IS
'出差天数';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL."DEPCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_BUSINESSREPORTDETAIL."DESTCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

/*==============================================================*/
/* Table: T_OA_BUSINESSTRIP                                     */
/*==============================================================*/
CREATE TABLE T_OA_BUSINESSTRIP  (
   BUSINESSTRIPID       NVARCHAR2(50)                   NOT NULL,
   "TEL"                NVARCHAR2(50),
   ISAGENT              NVARCHAR2(1)                   DEFAULT '0' NOT NULL,
   "ISCHARGE"           NVARCHAR2(1)                   DEFAULT '0' NOT NULL,
   "CHARGEMONEY"        NUMBER                         DEFAULT 0,
   CHECKSTATE           NVARCHAR2(1)                    NOT NULL,
   CONTENT              VARCHAR2(2000)                  NOT NULL,
   REMARKS              NVARCHAR2(200),
   "OWNERID"            NVARCHAR2(50)                   NOT NULL,
   "OWNERNAME"          NVARCHAR2(50)                   NOT NULL,
   "OWNERCOMPANYID"     NVARCHAR2(50)                   NOT NULL,
   "OWNERDEPARTMENTID"  NVARCHAR2(50)                   NOT NULL,
   "OWNERPOSTID"        NVARCHAR2(50)                   NOT NULL,
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATECOMPANYID      NVARCHAR2(50)                   NOT NULL,
   CREATEDEPARTMENTID   NVARCHAR2(50)                   NOT NULL,
   CREATEPOSTID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   "UPDATEUSERNAME"     NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_BUSINESSTRIP PRIMARY KEY (BUSINESSTRIPID)
);

COMMENT ON TABLE T_OA_BUSINESSTRIP IS
'出差申请';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.BUSINESSTRIPID IS
'出差申请ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."TEL" IS
'紧急联系电话';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.ISAGENT IS
'0:不启用，1:启用';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."ISCHARGE" IS
'0：无费用，1：有费用';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."CHARGEMONEY" IS
'借款总额';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CHECKSTATE IS
'0：未提交；1：审核通过；2：审核中；3：审核未通过';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CONTENT IS
'出差事由';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.REMARKS IS
'备注';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."OWNERID" IS
'出差人ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."OWNERNAME" IS
'出差人名称';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."OWNERCOMPANYID" IS
'所属公司';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."OWNERDEPARTMENTID" IS
'所属部门';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."OWNERPOSTID" IS
'所属岗位';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATECOMPANYID IS
'创建公司ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATEDEPARTMENTID IS
'创建部门ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATEPOSTID IS
'创建岗位ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_BUSINESSTRIP."UPDATEUSERNAME" IS
'修改人名';

COMMENT ON COLUMN T_OA_BUSINESSTRIP.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_BUSINESSTRIPDETAIL                               */
/*==============================================================*/
CREATE TABLE T_OA_BUSINESSTRIPDETAIL  (
   BUSINESSTRIPDETAILID NVARCHAR2(50)                   NOT NULL,
   BUSINESSTRIPID       NVARCHAR2(50)                   NOT NULL,
   STARTDATE            DATE                            NOT NULL,
   ENDDATE              DATE                            NOT NULL,
   "DEPCITY"            NVARCHAR2(50)                   NOT NULL,
   "DESTCITY"           NVARCHAR2(50)                   NOT NULL,
   CONSTRAINT PK_T_OA_BUSINESSTRIPDETAIL PRIMARY KEY (BUSINESSTRIPDETAILID)
);

COMMENT ON TABLE T_OA_BUSINESSTRIPDETAIL IS
'出差申请子表';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL.BUSINESSTRIPDETAILID IS
'申请子表ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL.BUSINESSTRIPID IS
'出差申请ID';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL.STARTDATE IS
'开始时间';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL.ENDDATE IS
'结束时间';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL."DEPCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_BUSINESSTRIPDETAIL."DESTCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

/*==============================================================*/
/* Table: T_OA_CANTAKETHEPLANELINE                              */
/*==============================================================*/
CREATE TABLE T_OA_CANTAKETHEPLANELINE  (
   CANTAKETHEPLANELINEID NVARCHAR2(50)                   NOT NULL,
   TRAVELSOLUTIONSID    NVARCHAR2(50),
   REGIONAL             NVARCHAR2(50),
   "DEPCITY"            NVARCHAR2(50)                   NOT NULL,
   "DESTCITY"           NVARCHAR2(50)                   NOT NULL,
   LANDTIME             NVARCHAR2(20),
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_CANTAKETHEPLANELINE PRIMARY KEY (CANTAKETHEPLANELINEID)
);

COMMENT ON TABLE T_OA_CANTAKETHEPLANELINE IS
'出差可乘坐飞机线路设置';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.CANTAKETHEPLANELINEID IS
'ID';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.TRAVELSOLUTIONSID IS
'方案id';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.REGIONAL IS
'例如：南区，在字典中定义';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE."DEPCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE."DESTCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.LANDTIME IS
'陆路所需时间';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_CANTAKETHEPLANELINE.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_PROGRAMAPPLICATIONS                              */
/*==============================================================*/
CREATE TABLE T_OA_PROGRAMAPPLICATIONS  (
   PROGRAMAPPLICATIONSID NVARCHAR2(50)                   NOT NULL,
   TRAVELSOLUTIONSID    NVARCHAR2(50),
   "COMPANYID"          NVARCHAR2(50),
   "OWNERCOMPANYID"     NVARCHAR2(50)                   NOT NULL,
   "OWNERDEPARTMENTID"  NVARCHAR2(50)                   NOT NULL,
   "OWNERPOSTID"        NVARCHAR2(50)                   NOT NULL,
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_PROGRAMAPPLICATIONS PRIMARY KEY (PROGRAMAPPLICATIONSID)
);

COMMENT ON TABLE T_OA_PROGRAMAPPLICATIONS IS
'出差方案应用';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.PROGRAMAPPLICATIONSID IS
'方案应用ID';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.TRAVELSOLUTIONSID IS
'方案id';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS."COMPANYID" IS
'公司ID';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS."OWNERCOMPANYID" IS
'所属公司';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS."OWNERDEPARTMENTID" IS
'所属部门';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS."OWNERPOSTID" IS
'所属岗位';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_PROGRAMAPPLICATIONS.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_REIMBURSEMENTDETAIL                              */
/*==============================================================*/
CREATE TABLE T_OA_REIMBURSEMENTDETAIL  (
   REIMBURSEMENTDETAILID NVARCHAR2(50)                   NOT NULL,
   TRAVELREIMBURSEMENTID NVARCHAR2(50),
   STARTDATE            DATE                            NOT NULL,
   ENDDATE              DATE                            NOT NULL,
   "DEPCITY"            NVARCHAR2(50)                   NOT NULL,
   "DESTCITY"           NVARCHAR2(50)                   NOT NULL,
   LANDTIME             NVARCHAR2(20),
   "BUSINESSDAYS"       NVARCHAR2(50),
   TYPEOFTRAVELTOOLS    NVARCHAR2(50),
   TAKETHETOOLLEVEL     NVARCHAR2(50),
   TRANSPORTCOSTS       NUMBER,
   ACCOMMODATION        NUMBER,
   "TRANSPORTATIONSUBSIDIES" NUMBER,
   "MEALSUBSIDIES"      NUMBER,
   OTHERCOSTS           NUMBER,
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_REIMBURSEMENTDETAIL PRIMARY KEY (REIMBURSEMENTDETAILID)
);

COMMENT ON TABLE T_OA_REIMBURSEMENTDETAIL IS
'出差报销子表';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.REIMBURSEMENTDETAILID IS
'REIMBURSEMENTDETAILID';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.TRAVELREIMBURSEMENTID IS
'出差报销ID';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.STARTDATE IS
'开始时间';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.ENDDATE IS
'结束时间';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL."DEPCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL."DESTCITY" IS
'通过SYS_TYPEGROUP_T获取地区定义名';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.LANDTIME IS
'陆路所需时间，从飞机线路设置里面带出来';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL."BUSINESSDAYS" IS
'总计出差的时间';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.TYPEOFTRAVELTOOLS IS
'乘坐的交通工具类型';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.TAKETHETOOLLEVEL IS
'交通工具的级别(例如：飞机头等舱)';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.TRANSPORTCOSTS IS
'乘坐交通工具费用';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.ACCOMMODATION IS
'住宿补贴费用';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL."TRANSPORTATIONSUBSIDIES" IS
'交通补贴费用';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL."MEALSUBSIDIES" IS
'餐费补贴';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.OTHERCOSTS IS
'其他费用';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_REIMBURSEMENTDETAIL.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_TAKETHESTANDARDTRANSPORT                         */
/*==============================================================*/
CREATE TABLE T_OA_TAKETHESTANDARDTRANSPORT  (
   TAKETHESTANDARDTRANSPORTID NVARCHAR2(50)                   NOT NULL,
   TRAVELSOLUTIONSID    NVARCHAR2(50),
   STARTPOSTLEVEL       NVARCHAR2(50),
   ENDPOSTLEVEL         NVARCHAR2(50),
   LANDTIME             NUMBER,
   TYPEOFTRAVELTOOLS    NVARCHAR2(50),
   TAKETHETOOLLEVEL     NVARCHAR2(50),
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_TAKETHESTANDARDTRANSPO PRIMARY KEY (TAKETHESTANDARDTRANSPORTID)
);

COMMENT ON TABLE T_OA_TAKETHESTANDARDTRANSPORT IS
'出差交通工具乘坐标准设置';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.TAKETHESTANDARDTRANSPORTID IS
'ID';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.TRAVELSOLUTIONSID IS
'方案id';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.STARTPOSTLEVEL IS
'岗位的等级，如（H级）';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.ENDPOSTLEVEL IS
'岗位的等级，如（H级）';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.LANDTIME IS
'陆路所需时间，从飞机线路设置里面带出来';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.TYPEOFTRAVELTOOLS IS
'工具的类型(如：飞机)';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.TAKETHETOOLLEVEL IS
'例如：飞机（头等舱）';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_TAKETHESTANDARDTRANSPORT.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_TRAVELREIMBURSEMENT                              */
/*==============================================================*/
CREATE TABLE T_OA_TRAVELREIMBURSEMENT  (
   TRAVELREIMBURSEMENTID NVARCHAR2(50)                   NOT NULL,
   BUSINESSREPORTID     NVARCHAR2(50),
   CLAIMSWERE           NVARCHAR2(50),
   CLAIMSWERENAME       NVARCHAR2(50)                   NOT NULL,
   REIMBURSEMENTTIME    DATE,
   COMPUTINGTIME        NVARCHAR2(50),
   "TEL"                NVARCHAR2(50)                   NOT NULL,
   THETOTALCOST         NUMBER,
   CHECKSTATE           NVARCHAR2(1)                   DEFAULT '0' NOT NULL,
   REMARKS              NVARCHAR2(200),
   "OWNERID"            NVARCHAR2(50)                   NOT NULL,
   "OWNERNAME"          NVARCHAR2(50)                   NOT NULL,
   "OWNERCOMPANYID"     NVARCHAR2(50)                   NOT NULL,
   "OWNERDEPARTMENTID"  NVARCHAR2(50)                   NOT NULL,
   "OWNERPOSTID"        NVARCHAR2(50)                   NOT NULL,
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATECOMPANYID      NVARCHAR2(50)                   NOT NULL,
   CREATEDEPARTMENTID   NVARCHAR2(50)                   NOT NULL,
   CREATEPOSTID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_TRAVELREIMBURSEMENT PRIMARY KEY (TRAVELREIMBURSEMENTID)
);

COMMENT ON TABLE T_OA_TRAVELREIMBURSEMENT IS
'出差报销';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.TRAVELREIMBURSEMENTID IS
'出差报销ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.BUSINESSREPORTID IS
'出差报告ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CLAIMSWERE IS
'报销人';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CLAIMSWERENAME IS
'报销姓名';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.REIMBURSEMENTTIME IS
'报销时间';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.COMPUTINGTIME IS
'总计出差的时间';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."TEL" IS
'联系电话';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.THETOTALCOST IS
'总费用';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CHECKSTATE IS
'0：未提交；1：审核通过；2：审核中；3：审核未通过';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.REMARKS IS
'备注';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."OWNERID" IS
'所属人ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."OWNERNAME" IS
'所属人名称';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."OWNERCOMPANYID" IS
'所属公司';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."OWNERDEPARTMENTID" IS
'所属部门';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT."OWNERPOSTID" IS
'所属岗位';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATECOMPANYID IS
'创建公司ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATEDEPARTMENTID IS
'创建部门ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATEPOSTID IS
'创建岗位ID';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_TRAVELREIMBURSEMENT.UPDATEDATE IS
'修改时间';

/*==============================================================*/
/* Table: T_OA_TRAVELSOLUTIONS                                  */
/*==============================================================*/
CREATE TABLE T_OA_TRAVELSOLUTIONS  (
   TRAVELSOLUTIONSID    NVARCHAR2(50)                   NOT NULL,
   PROGRAMMENAME        NVARCHAR2(50),
   ANDFROMTHATDAY       NVARCHAR2(50),
   CUSTOMDAY            NVARCHAR2(20),
   CUSTOMHALFDAY        NVARCHAR2(20),
   "RANGEPOSTLEVEL"     NVARCHAR2(20)                   NOT NULL,
   "RANGEDAYS"          NVARCHAR2(20)                   NOT NULL,
   "MINIMUMDAYS"        NVARCHAR2(20)                   NOT NULL,
   "SUBSIDYSTANDARDS"   NVARCHAR2(20)                   NOT NULL,
   "MAXIMUMRANGEDAYS"   NVARCHAR2(20)                   NOT NULL,
   "MINIMUMINTERVALDAYS" NVARCHAR2(20)                   NOT NULL,
   "INTERVALRATIO"      NVARCHAR2(20)                   NOT NULL,
   "MAXIMUMDAYS"        NVARCHAR2(20)                   NOT NULL,
   "OWNERCOMPANYID"     NVARCHAR2(50)                   NOT NULL,
   "OWNERDEPARTMENTID"  NVARCHAR2(50)                   NOT NULL,
   "OWNERPOSTID"        NVARCHAR2(50)                   NOT NULL,
   CREATEUSERID         NVARCHAR2(50)                   NOT NULL,
   CREATEUSERNAME       NVARCHAR2(50)                   NOT NULL,
   CREATECOMPANYID      NVARCHAR2(50)                   NOT NULL,
   CREATEDEPARTMENTID   NVARCHAR2(50)                   NOT NULL,
   CREATEPOSTID         NVARCHAR2(50)                   NOT NULL,
   CREATEDATE           DATE                           DEFAULT SYSDATE NOT NULL,
   UPDATEUSERID         NVARCHAR2(50),
   "UPDATEUSERNAME"     NVARCHAR2(50),
   UPDATEDATE           DATE,
   CONSTRAINT PK_T_OA_TRAVELSOLUTIONS PRIMARY KEY (TRAVELSOLUTIONSID)
);

COMMENT ON TABLE T_OA_TRAVELSOLUTIONS IS
'出差方案';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.TRAVELSOLUTIONSID IS
'方案id';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.PROGRAMMENAME IS
'当天往返是否算一天';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.ANDFROMTHATDAY IS
'当天往返是否算一天';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CUSTOMDAY IS
'多少小时算一天';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CUSTOMHALFDAY IS
'多少小时算半天';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."RANGEPOSTLEVEL" IS
'大于一定级别的不能申请费用报销';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."RANGEDAYS" IS
'多少范围的天数内能够报销';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."MINIMUMDAYS" IS
'最小天数(定义小于天数的报销标准)';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."SUBSIDYSTANDARDS" IS
'补贴标准(最小天数的补贴标准)';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."MAXIMUMRANGEDAYS" IS
'区间最大天数';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."MINIMUMINTERVALDAYS" IS
'区间最小天数';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."INTERVALRATIO" IS
'区间比例';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."MAXIMUMDAYS" IS
'最大天数';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."OWNERCOMPANYID" IS
'所属公司';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."OWNERDEPARTMENTID" IS
'所属部门';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."OWNERPOSTID" IS
'所属岗位';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATEUSERID IS
'创建人';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATEUSERNAME IS
'创建人名';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATECOMPANYID IS
'创建公司ID';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATEDEPARTMENTID IS
'创建部门ID';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATEPOSTID IS
'创建岗位ID';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.CREATEDATE IS
'创建时间';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.UPDATEUSERID IS
'修改人';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS."UPDATEUSERNAME" IS
'修改人名';

COMMENT ON COLUMN T_OA_TRAVELSOLUTIONS.UPDATEDATE IS
'修改时间';

ALTER TABLE "T_OA_AREAALLOWANCE"
   ADD CONSTRAINT "FK_AREADIFFERENCE_T_OA_ARE" FOREIGN KEY ("AREADIFFERENCEID")
      REFERENCES "T_OA_AREADIFFERENCE" ("AREADIFFERENCEID");

ALTER TABLE "T_OA_AREACITY"
   ADD CONSTRAINT "FK_T_OA_ARE_AREACITY" FOREIGN KEY ("AREADIFFERENCEID")
      REFERENCES "T_OA_AREADIFFERENCE" ("AREADIFFERENCEID");

ALTER TABLE T_OA_BUSINESSREPORT
   ADD CONSTRAINT FK_BUSINESSTRIP_T_OA_BUS FOREIGN KEY (BUSINESSTRIPID)
      REFERENCES T_OA_BUSINESSTRIP (BUSINESSTRIPID);

ALTER TABLE T_OA_BUSINESSREPORTDETAIL
   ADD CONSTRAINT FK_T_OA_REPORTDETAIL_T_OA_BUS FOREIGN KEY (BUSINESSREPORTID)
      REFERENCES T_OA_BUSINESSREPORT (BUSINESSREPORTID);

ALTER TABLE T_OA_BUSINESSTRIPDETAIL
   ADD CONSTRAINT FK_T_OA_BUS_T_OA_BUSDETAIL FOREIGN KEY (BUSINESSTRIPID)
      REFERENCES T_OA_BUSINESSTRIP (BUSINESSTRIPID);

ALTER TABLE T_OA_CANTAKETHEPLANELINE
   ADD CONSTRAINT FK_T_OA_CAN_REFERENCE_T_OA_TRA FOREIGN KEY (TRAVELSOLUTIONSID)
      REFERENCES T_OA_TRAVELSOLUTIONS (TRAVELSOLUTIONSID);

ALTER TABLE T_OA_PROGRAMAPPLICATIONS
   ADD CONSTRAINT FK_T_OA_PRO_REFERENCE_T_OA_TRA FOREIGN KEY (TRAVELSOLUTIONSID)
      REFERENCES T_OA_TRAVELSOLUTIONS (TRAVELSOLUTIONSID);

ALTER TABLE T_OA_REIMBURSEMENTDETAIL
   ADD CONSTRAINT FK_T_OA_REI_REFERENCE_T_OA_TRA FOREIGN KEY (TRAVELREIMBURSEMENTID)
      REFERENCES T_OA_TRAVELREIMBURSEMENT (TRAVELREIMBURSEMENTID);

ALTER TABLE T_OA_TAKETHESTANDARDTRANSPORT
   ADD CONSTRAINT FK_T_OA_TAK_REFERENCE_T_OA_TRA FOREIGN KEY (TRAVELSOLUTIONSID)
      REFERENCES T_OA_TRAVELSOLUTIONS (TRAVELSOLUTIONSID);

ALTER TABLE T_OA_TRAVELREIMBURSEMENT
   ADD CONSTRAINT FK_T_OA_TRA_REFERENCE_T_OA_BUS FOREIGN KEY (BUSINESSREPORTID)
      REFERENCES T_OA_BUSINESSREPORT (BUSINESSREPORTID);

