//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SMT.SAAS.Platform.EmployeeInfoWS {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_EMPLOYEEDETAIL", Namespace="http://schemas.datacontract.org/2004/07/SMT.HRM.CustomModel")]
    public partial class V_EMPLOYEEDETAIL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CURRENTADDRESSField;
        
        private string EMPLOYEECODEField;
        
        private string EMPLOYEEENAMEField;
        
        private string EMPLOYEEIDField;
        
        private string EMPLOYEENAMEField;
        
        private System.Collections.ObjectModel.ObservableCollection<SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEPOSTBRIEF> EMPLOYEEPOSTSField;
        
        private string EMPLOYEESTATEField;
        
        private string MOBILEField;
        
        private string OFFICEPHONEField;
        
        private byte[] PHOTOField;
        
        private string POSTIDField;
        
        private string SEXField;
        
        private string URGENCYCONTACTField;
        
        private string URGENCYPERSONField;
        
        private int WORKAGEField;
        
        private SMT.SAAS.Platform.EmployeeInfoWS.V_UserLogin sysuserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURRENTADDRESS {
            get {
                return this.CURRENTADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.CURRENTADDRESSField, value) != true)) {
                    this.CURRENTADDRESSField = value;
                    this.RaisePropertyChanged("CURRENTADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEECODE {
            get {
                return this.EMPLOYEECODEField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEECODEField, value) != true)) {
                    this.EMPLOYEECODEField = value;
                    this.RaisePropertyChanged("EMPLOYEECODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEEENAME {
            get {
                return this.EMPLOYEEENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEEENAMEField, value) != true)) {
                    this.EMPLOYEEENAMEField = value;
                    this.RaisePropertyChanged("EMPLOYEEENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEEID {
            get {
                return this.EMPLOYEEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEEIDField, value) != true)) {
                    this.EMPLOYEEIDField = value;
                    this.RaisePropertyChanged("EMPLOYEEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEENAME {
            get {
                return this.EMPLOYEENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEENAMEField, value) != true)) {
                    this.EMPLOYEENAMEField = value;
                    this.RaisePropertyChanged("EMPLOYEENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEPOSTBRIEF> EMPLOYEEPOSTS {
            get {
                return this.EMPLOYEEPOSTSField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEEPOSTSField, value) != true)) {
                    this.EMPLOYEEPOSTSField = value;
                    this.RaisePropertyChanged("EMPLOYEEPOSTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEESTATE {
            get {
                return this.EMPLOYEESTATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEESTATEField, value) != true)) {
                    this.EMPLOYEESTATEField = value;
                    this.RaisePropertyChanged("EMPLOYEESTATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOBILE {
            get {
                return this.MOBILEField;
            }
            set {
                if ((object.ReferenceEquals(this.MOBILEField, value) != true)) {
                    this.MOBILEField = value;
                    this.RaisePropertyChanged("MOBILE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OFFICEPHONE {
            get {
                return this.OFFICEPHONEField;
            }
            set {
                if ((object.ReferenceEquals(this.OFFICEPHONEField, value) != true)) {
                    this.OFFICEPHONEField = value;
                    this.RaisePropertyChanged("OFFICEPHONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PHOTO {
            get {
                return this.PHOTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PHOTOField, value) != true)) {
                    this.PHOTOField = value;
                    this.RaisePropertyChanged("PHOTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POSTID {
            get {
                return this.POSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.POSTIDField, value) != true)) {
                    this.POSTIDField = value;
                    this.RaisePropertyChanged("POSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEX {
            get {
                return this.SEXField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXField, value) != true)) {
                    this.SEXField = value;
                    this.RaisePropertyChanged("SEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URGENCYCONTACT {
            get {
                return this.URGENCYCONTACTField;
            }
            set {
                if ((object.ReferenceEquals(this.URGENCYCONTACTField, value) != true)) {
                    this.URGENCYCONTACTField = value;
                    this.RaisePropertyChanged("URGENCYCONTACT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URGENCYPERSON {
            get {
                return this.URGENCYPERSONField;
            }
            set {
                if ((object.ReferenceEquals(this.URGENCYPERSONField, value) != true)) {
                    this.URGENCYPERSONField = value;
                    this.RaisePropertyChanged("URGENCYPERSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WORKAGE {
            get {
                return this.WORKAGEField;
            }
            set {
                if ((this.WORKAGEField.Equals(value) != true)) {
                    this.WORKAGEField = value;
                    this.RaisePropertyChanged("WORKAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SAAS.Platform.EmployeeInfoWS.V_UserLogin sysuser {
            get {
                return this.sysuserField;
            }
            set {
                if ((object.ReferenceEquals(this.sysuserField, value) != true)) {
                    this.sysuserField = value;
                    this.RaisePropertyChanged("sysuser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_UserLogin", Namespace="http://schemas.datacontract.org/2004/07/SMT.HRM.CustomModel")]
    public partial class V_UserLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EMPLOYEEIDField;
        
        private string ISMANAGERField;
        
        private string LOGINRECORDIDField;
        
        private string SYSUSERIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEEID {
            get {
                return this.EMPLOYEEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEEIDField, value) != true)) {
                    this.EMPLOYEEIDField = value;
                    this.RaisePropertyChanged("EMPLOYEEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISMANAGER {
            get {
                return this.ISMANAGERField;
            }
            set {
                if ((object.ReferenceEquals(this.ISMANAGERField, value) != true)) {
                    this.ISMANAGERField = value;
                    this.RaisePropertyChanged("ISMANAGER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGINRECORDID {
            get {
                return this.LOGINRECORDIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINRECORDIDField, value) != true)) {
                    this.LOGINRECORDIDField = value;
                    this.RaisePropertyChanged("LOGINRECORDID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYSUSERID {
            get {
                return this.SYSUSERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSUSERIDField, value) != true)) {
                    this.SYSUSERIDField = value;
                    this.RaisePropertyChanged("SYSUSERID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_EMPLOYEEPOSTBRIEF", Namespace="http://schemas.datacontract.org/2004/07/SMT.HRM.CustomModel")]
    public partial class V_EMPLOYEEPOSTBRIEF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CompanyIDField;
        
        private string CompanyNameField;
        
        private string DepartmentIDField;
        
        private string DepartmentNameField;
        
        private string EMPLOYEEPOSTIDField;
        
        private string ISAGENCYField;
        
        private string POSTIDField;
        
        private System.Nullable<decimal> POSTLEVELField;
        
        private string PostNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIDField, value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPLOYEEPOSTID {
            get {
                return this.EMPLOYEEPOSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPLOYEEPOSTIDField, value) != true)) {
                    this.EMPLOYEEPOSTIDField = value;
                    this.RaisePropertyChanged("EMPLOYEEPOSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISAGENCY {
            get {
                return this.ISAGENCYField;
            }
            set {
                if ((object.ReferenceEquals(this.ISAGENCYField, value) != true)) {
                    this.ISAGENCYField = value;
                    this.RaisePropertyChanged("ISAGENCY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POSTID {
            get {
                return this.POSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.POSTIDField, value) != true)) {
                    this.POSTIDField = value;
                    this.RaisePropertyChanged("POSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> POSTLEVEL {
            get {
                return this.POSTLEVELField;
            }
            set {
                if ((this.POSTLEVELField.Equals(value) != true)) {
                    this.POSTLEVELField = value;
                    this.RaisePropertyChanged("POSTLEVEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostName {
            get {
                return this.PostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PostNameField, value) != true)) {
                    this.PostNameField = value;
                    this.RaisePropertyChanged("PostName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="EmployeeInfoWS.EmployeeInfoService")]
    public interface EmployeeInfoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:EmployeeInfoService/getEmployeeInfobyLogin", ReplyAction="urn:EmployeeInfoService/getEmployeeInfobyLoginResponse")]
        System.IAsyncResult BegingetEmployeeInfobyLogin(string employeeid, System.AsyncCallback callback, object asyncState);
        
        SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL EndgetEmployeeInfobyLogin(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeInfoServiceChannel : SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEmployeeInfobyLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getEmployeeInfobyLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeInfoServiceClient : System.ServiceModel.ClientBase<SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService>, SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService {
        
        private BeginOperationDelegate onBegingetEmployeeInfobyLoginDelegate;
        
        private EndOperationDelegate onEndgetEmployeeInfobyLoginDelegate;
        
        private System.Threading.SendOrPostCallback ongetEmployeeInfobyLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public EmployeeInfoServiceClient() {
        }
        
        public EmployeeInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<getEmployeeInfobyLoginCompletedEventArgs> getEmployeeInfobyLoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService.BegingetEmployeeInfobyLogin(string employeeid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetEmployeeInfobyLogin(employeeid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService.EndgetEmployeeInfobyLogin(System.IAsyncResult result) {
            return base.Channel.EndgetEmployeeInfobyLogin(result);
        }
        
        private System.IAsyncResult OnBegingetEmployeeInfobyLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string employeeid = ((string)(inValues[0]));
            return ((SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService)(this)).BegingetEmployeeInfobyLogin(employeeid, callback, asyncState);
        }
        
        private object[] OnEndgetEmployeeInfobyLogin(System.IAsyncResult result) {
            SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL retVal = ((SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService)(this)).EndgetEmployeeInfobyLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetEmployeeInfobyLoginCompleted(object state) {
            if ((this.getEmployeeInfobyLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getEmployeeInfobyLoginCompleted(this, new getEmployeeInfobyLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getEmployeeInfobyLoginAsync(string employeeid) {
            this.getEmployeeInfobyLoginAsync(employeeid, null);
        }
        
        public void getEmployeeInfobyLoginAsync(string employeeid, object userState) {
            if ((this.onBegingetEmployeeInfobyLoginDelegate == null)) {
                this.onBegingetEmployeeInfobyLoginDelegate = new BeginOperationDelegate(this.OnBegingetEmployeeInfobyLogin);
            }
            if ((this.onEndgetEmployeeInfobyLoginDelegate == null)) {
                this.onEndgetEmployeeInfobyLoginDelegate = new EndOperationDelegate(this.OnEndgetEmployeeInfobyLogin);
            }
            if ((this.ongetEmployeeInfobyLoginCompletedDelegate == null)) {
                this.ongetEmployeeInfobyLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetEmployeeInfobyLoginCompleted);
            }
            base.InvokeAsync(this.onBegingetEmployeeInfobyLoginDelegate, new object[] {
                        employeeid}, this.onEndgetEmployeeInfobyLoginDelegate, this.ongetEmployeeInfobyLoginCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService CreateChannel() {
            return new EmployeeInfoServiceClientChannel(this);
        }
        
        private class EmployeeInfoServiceClientChannel : ChannelBase<SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService>, SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService {
            
            public EmployeeInfoServiceClientChannel(System.ServiceModel.ClientBase<SMT.SAAS.Platform.EmployeeInfoWS.EmployeeInfoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetEmployeeInfobyLogin(string employeeid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = employeeid;
                System.IAsyncResult _result = base.BeginInvoke("getEmployeeInfobyLogin", _args, callback, asyncState);
                return _result;
            }
            
            public SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL EndgetEmployeeInfobyLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL _result = ((SMT.SAAS.Platform.EmployeeInfoWS.V_EMPLOYEEDETAIL)(base.EndInvoke("getEmployeeInfobyLogin", _args, result)));
                return _result;
            }
        }
    }
}
