//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.SaaS.BLLCommonServices.FileUploadWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFile", Namespace="http://schemas.datacontract.org/2004/07/SMT.FileUpLoad.Service")]
    [System.SerializableAttribute()]
    public partial class UserFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BytesUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal INDEXLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERCOMPANYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERDEPARTMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERPOSTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SavePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmtFileListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UploadSpeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BytesUploaded {
            get {
                return this.BytesUploadedField;
            }
            set {
                if ((this.BytesUploadedField.Equals(value) != true)) {
                    this.BytesUploadedField = value;
                    this.RaisePropertyChanged("BytesUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateName {
            get {
                return this.CreateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateNameField, value) != true)) {
                    this.CreateNameField = value;
                    this.RaisePropertyChanged("CreateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileUrl {
            get {
                return this.FileUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FileUrlField, value) != true)) {
                    this.FileUrlField = value;
                    this.RaisePropertyChanged("FileUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal INDEXL {
            get {
                return this.INDEXLField;
            }
            set {
                if ((this.INDEXLField.Equals(value) != true)) {
                    this.INDEXLField = value;
                    this.RaisePropertyChanged("INDEXL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumber {
            get {
                return this.MaxNumberField;
            }
            set {
                if ((this.MaxNumberField.Equals(value) != true)) {
                    this.MaxNumberField = value;
                    this.RaisePropertyChanged("MaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxSize {
            get {
                return this.MaxSizeField;
            }
            set {
                if ((this.MaxSizeField.Equals(value) != true)) {
                    this.MaxSizeField = value;
                    this.RaisePropertyChanged("MaxSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelCode {
            get {
                return this.ModelCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelCodeField, value) != true)) {
                    this.ModelCodeField = value;
                    this.RaisePropertyChanged("ModelCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERCOMPANYID {
            get {
                return this.OWNERCOMPANYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERCOMPANYIDField, value) != true)) {
                    this.OWNERCOMPANYIDField = value;
                    this.RaisePropertyChanged("OWNERCOMPANYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERDEPARTMENTID {
            get {
                return this.OWNERDEPARTMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERDEPARTMENTIDField, value) != true)) {
                    this.OWNERDEPARTMENTIDField = value;
                    this.RaisePropertyChanged("OWNERDEPARTMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERID {
            get {
                return this.OWNERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERIDField, value) != true)) {
                    this.OWNERIDField = value;
                    this.RaisePropertyChanged("OWNERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERPOSTID {
            get {
                return this.OWNERPOSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERPOSTIDField, value) != true)) {
                    this.OWNERPOSTIDField = value;
                    this.RaisePropertyChanged("OWNERPOSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SavePath {
            get {
                return this.SavePathField;
            }
            set {
                if ((object.ReferenceEquals(this.SavePathField, value) != true)) {
                    this.SavePathField = value;
                    this.RaisePropertyChanged("SavePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmtFileListId {
            get {
                return this.SmtFileListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SmtFileListIdField, value) != true)) {
                    this.SmtFileListIdField = value;
                    this.RaisePropertyChanged("SmtFileListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemCode {
            get {
                return this.SystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemCodeField, value) != true)) {
                    this.SystemCodeField = value;
                    this.RaisePropertyChanged("SystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailUrl {
            get {
                return this.ThumbnailUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailUrlField, value) != true)) {
                    this.ThumbnailUrlField = value;
                    this.RaisePropertyChanged("ThumbnailUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateName {
            get {
                return this.UpdateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateNameField, value) != true)) {
                    this.UpdateNameField = value;
                    this.RaisePropertyChanged("UpdateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UploadSpeed {
            get {
                return this.UploadSpeedField;
            }
            set {
                if ((this.UploadSpeedField.Equals(value) != true)) {
                    this.UploadSpeedField = value;
                    this.RaisePropertyChanged("UploadSpeed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallBackResult", Namespace="http://schemas.datacontract.org/2004/07/SMT.FileUpLoad.Service")]
    [System.SerializableAttribute()]
    public partial class CallBackResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownloadUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMT.SaaS.BLLCommonServices.FileUploadWS.SMT_FILELIST[] FileListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownloadUrl {
            get {
                return this.DownloadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DownloadUrlField, value) != true)) {
                    this.DownloadUrlField = value;
                    this.RaisePropertyChanged("DownloadUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SaaS.BLLCommonServices.FileUploadWS.SMT_FILELIST[] FileList {
            get {
                return this.FileListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileListField, value) != true)) {
                    this.FileListField = value;
                    this.RaisePropertyChanged("FileList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMT_FILELIST", Namespace="http://schemas.datacontract.org/2004/07/SMT_FU_EFModel", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SMT_FILELIST : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPLICATIONIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CREATETIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEUSERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FILESIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILETYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FILEURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FORMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> INDEXLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODELCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERCOMPANYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERDEPARTMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERPOSTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REMARKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMTFILELISTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYSTEMCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string THUMBNAILURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UPDATETIMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLICATIONID {
            get {
                return this.APPLICATIONIDField;
            }
            set {
                if ((object.ReferenceEquals(this.APPLICATIONIDField, value) != true)) {
                    this.APPLICATIONIDField = value;
                    this.RaisePropertyChanged("APPLICATIONID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANYCODE {
            get {
                return this.COMPANYCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYCODEField, value) != true)) {
                    this.COMPANYCODEField = value;
                    this.RaisePropertyChanged("COMPANYCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANYNAME {
            get {
                return this.COMPANYNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYNAMEField, value) != true)) {
                    this.COMPANYNAMEField = value;
                    this.RaisePropertyChanged("COMPANYNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATENAME {
            get {
                return this.CREATENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATENAMEField, value) != true)) {
                    this.CREATENAMEField = value;
                    this.RaisePropertyChanged("CREATENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CREATETIME {
            get {
                return this.CREATETIMEField;
            }
            set {
                if ((this.CREATETIMEField.Equals(value) != true)) {
                    this.CREATETIMEField = value;
                    this.RaisePropertyChanged("CREATETIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEUSERID {
            get {
                return this.CREATEUSERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEUSERIDField, value) != true)) {
                    this.CREATEUSERIDField = value;
                    this.RaisePropertyChanged("CREATEUSERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILENAME {
            get {
                return this.FILENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FILENAMEField, value) != true)) {
                    this.FILENAMEField = value;
                    this.RaisePropertyChanged("FILENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FILESIZE {
            get {
                return this.FILESIZEField;
            }
            set {
                if ((this.FILESIZEField.Equals(value) != true)) {
                    this.FILESIZEField = value;
                    this.RaisePropertyChanged("FILESIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILETYPE {
            get {
                return this.FILETYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.FILETYPEField, value) != true)) {
                    this.FILETYPEField = value;
                    this.RaisePropertyChanged("FILETYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILEURL {
            get {
                return this.FILEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.FILEURLField, value) != true)) {
                    this.FILEURLField = value;
                    this.RaisePropertyChanged("FILEURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FORMID {
            get {
                return this.FORMIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMIDField, value) != true)) {
                    this.FORMIDField = value;
                    this.RaisePropertyChanged("FORMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> INDEXL {
            get {
                return this.INDEXLField;
            }
            set {
                if ((this.INDEXLField.Equals(value) != true)) {
                    this.INDEXLField = value;
                    this.RaisePropertyChanged("INDEXL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MODELCODE {
            get {
                return this.MODELCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.MODELCODEField, value) != true)) {
                    this.MODELCODEField = value;
                    this.RaisePropertyChanged("MODELCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERCOMPANYID {
            get {
                return this.OWNERCOMPANYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERCOMPANYIDField, value) != true)) {
                    this.OWNERCOMPANYIDField = value;
                    this.RaisePropertyChanged("OWNERCOMPANYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERDEPARTMENTID {
            get {
                return this.OWNERDEPARTMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERDEPARTMENTIDField, value) != true)) {
                    this.OWNERDEPARTMENTIDField = value;
                    this.RaisePropertyChanged("OWNERDEPARTMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERID {
            get {
                return this.OWNERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERIDField, value) != true)) {
                    this.OWNERIDField = value;
                    this.RaisePropertyChanged("OWNERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERPOSTID {
            get {
                return this.OWNERPOSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERPOSTIDField, value) != true)) {
                    this.OWNERPOSTIDField = value;
                    this.RaisePropertyChanged("OWNERPOSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD {
            get {
                return this.PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORDField, value) != true)) {
                    this.PASSWORDField = value;
                    this.RaisePropertyChanged("PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REMARK {
            get {
                return this.REMARKField;
            }
            set {
                if ((object.ReferenceEquals(this.REMARKField, value) != true)) {
                    this.REMARKField = value;
                    this.RaisePropertyChanged("REMARK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTFILELISTID {
            get {
                return this.SMTFILELISTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SMTFILELISTIDField, value) != true)) {
                    this.SMTFILELISTIDField = value;
                    this.RaisePropertyChanged("SMTFILELISTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYSTEMCODE {
            get {
                return this.SYSTEMCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSTEMCODEField, value) != true)) {
                    this.SYSTEMCODEField = value;
                    this.RaisePropertyChanged("SYSTEMCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string THUMBNAILURL {
            get {
                return this.THUMBNAILURLField;
            }
            set {
                if ((object.ReferenceEquals(this.THUMBNAILURLField, value) != true)) {
                    this.THUMBNAILURLField = value;
                    this.RaisePropertyChanged("THUMBNAILURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATENAME {
            get {
                return this.UPDATENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATENAMEField, value) != true)) {
                    this.UPDATENAMEField = value;
                    this.RaisePropertyChanged("UPDATENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UPDATETIME {
            get {
                return this.UPDATETIMEField;
            }
            set {
                if ((this.UPDATETIMEField.Equals(value) != true)) {
                    this.UPDATETIMEField = value;
                    this.RaisePropertyChanged("UPDATETIME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileUploadWS.IUploadService")]
    public interface IUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetCompanyFileSetInfo", ReplyAction="http://tempuri.org/IUploadService/GetCompanyFileSetInfoResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile GetCompanyFileSetInfo(string companycode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetCompanyFileByCompanyCodeAndName", ReplyAction="http://tempuri.org/IUploadService/GetCompanyFileByCompanyCodeAndNameResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile GetCompanyFileByCompanyCodeAndName(string companycode, string CompanyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/SaveUpLoadFile", ReplyAction="http://tempuri.org/IUploadService/SaveUpLoadFileResponse")]
        string SaveUpLoadFile(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, byte[] data, int BytesUploaded, int dataLength, bool firstChunk, bool lastChunk, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/SaveUploadFileForMvc", ReplyAction="http://tempuri.org/IUploadService/SaveUploadFileForMvcResponse")]
        string SaveUploadFileForMvc(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/SaveUpLoadFileIsExist", ReplyAction="http://tempuri.org/IUploadService/SaveUpLoadFileIsExistResponse")]
        string SaveUpLoadFileIsExist(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, byte[] data, int BytesUploaded, int dataLength, bool firstChunk, bool lastChunk, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/CancelUpload", ReplyAction="http://tempuri.org/IUploadService/CancelUploadResponse")]
        void CancelUpload(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/CheckFileExists", ReplyAction="http://tempuri.org/IUploadService/CheckFileExistsResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile CheckFileExists(SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model, string md5Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileListByCompanyCode", ReplyAction="http://tempuri.org/IUploadService/GetFileListByCompanyCodeResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByCompanyCode(string companycode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileListBySystemCode", ReplyAction="http://tempuri.org/IUploadService/GetFileListBySystemCodeResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListBySystemCode(string companycode, string systemcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileListByModelCode", ReplyAction="http://tempuri.org/IUploadService/GetFileListByModelCodeResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByModelCode(string companycode, string systemcode, string modelcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileListByApplicationID", ReplyAction="http://tempuri.org/IUploadService/GetFileListByApplicationIDResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByApplicationID(string companycode, string systemcode, string modelcode, string applicationid, string createname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileListByOnlyApplicationID", ReplyAction="http://tempuri.org/IUploadService/GetFileListByOnlyApplicationIDResponse")]
        SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByOnlyApplicationID(string applicationid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFile", ReplyAction="http://tempuri.org/IUploadService/DeleteFileResponse")]
        string DeleteFile(string smtfilelistid, string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByUrl", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByUrlResponse")]
        string DeleteFileByUrl(string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByApplicationID", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByApplicationIDResponse")]
        string DeleteFileByApplicationID(string companycode, string systemcode, string modelcode, string applicationid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByModelCode", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByModelCodeResponse")]
        string DeleteFileByModelCode(string companycode, string systemcode, string modelcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileBySystemCode", ReplyAction="http://tempuri.org/IUploadService/DeleteFileBySystemCodeResponse")]
        string DeleteFileBySystemCode(string companycode, string systemcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByCompanycode", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByCompanycodeResponse")]
        string DeleteFileByCompanycode(string companycode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByOnlyApplicationID", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByOnlyApplicationIDResponse")]
        string DeleteFileByOnlyApplicationID(string applicationid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DeleteFileByApplicationIDAndFileName", ReplyAction="http://tempuri.org/IUploadService/DeleteFileByApplicationIDAndFileNameResponse")]
        string DeleteFileByApplicationIDAndFileName(string applicationid, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/CreateCompanyDirectory", ReplyAction="http://tempuri.org/IUploadService/CreateCompanyDirectoryResponse")]
        string CreateCompanyDirectory(string companyID, string companyName, string companyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadServiceChannel : SMT.SaaS.BLLCommonServices.FileUploadWS.IUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceClient : System.ServiceModel.ClientBase<SMT.SaaS.BLLCommonServices.FileUploadWS.IUploadService>, SMT.SaaS.BLLCommonServices.FileUploadWS.IUploadService {
        
        public UploadServiceClient() {
        }
        
        public UploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile GetCompanyFileSetInfo(string companycode) {
            return base.Channel.GetCompanyFileSetInfo(companycode);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile GetCompanyFileByCompanyCodeAndName(string companycode, string CompanyName) {
            return base.Channel.GetCompanyFileByCompanyCodeAndName(companycode, CompanyName);
        }
        
        public string SaveUpLoadFile(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, byte[] data, int BytesUploaded, int dataLength, bool firstChunk, bool lastChunk, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model) {
            return base.Channel.SaveUpLoadFile(strSystemCode, strModelCode, strFileName, strMd5Name, strID, strGuid, data, BytesUploaded, dataLength, firstChunk, lastChunk, strCreateUserID, model);
        }
        
        public string SaveUploadFileForMvc(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model) {
            return base.Channel.SaveUploadFileForMvc(strSystemCode, strModelCode, strFileName, strMd5Name, strID, strGuid, strCreateUserID, model);
        }
        
        public string SaveUpLoadFileIsExist(string strSystemCode, string strModelCode, string strFileName, string strMd5Name, string strID, string strGuid, byte[] data, int BytesUploaded, int dataLength, bool firstChunk, bool lastChunk, string strCreateUserID, SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model) {
            return base.Channel.SaveUpLoadFileIsExist(strSystemCode, strModelCode, strFileName, strMd5Name, strID, strGuid, data, BytesUploaded, dataLength, firstChunk, lastChunk, strCreateUserID, model);
        }
        
        public void CancelUpload(string filename) {
            base.Channel.CancelUpload(filename);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile CheckFileExists(SMT.SaaS.BLLCommonServices.FileUploadWS.UserFile model, string md5Name) {
            return base.Channel.CheckFileExists(model, md5Name);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByCompanyCode(string companycode) {
            return base.Channel.GetFileListByCompanyCode(companycode);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListBySystemCode(string companycode, string systemcode) {
            return base.Channel.GetFileListBySystemCode(companycode, systemcode);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByModelCode(string companycode, string systemcode, string modelcode) {
            return base.Channel.GetFileListByModelCode(companycode, systemcode, modelcode);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByApplicationID(string companycode, string systemcode, string modelcode, string applicationid, string createname) {
            return base.Channel.GetFileListByApplicationID(companycode, systemcode, modelcode, applicationid, createname);
        }
        
        public SMT.SaaS.BLLCommonServices.FileUploadWS.CallBackResult GetFileListByOnlyApplicationID(string applicationid) {
            return base.Channel.GetFileListByOnlyApplicationID(applicationid);
        }
        
        public string DeleteFile(string smtfilelistid, string filepath) {
            return base.Channel.DeleteFile(smtfilelistid, filepath);
        }
        
        public string DeleteFileByUrl(string filepath) {
            return base.Channel.DeleteFileByUrl(filepath);
        }
        
        public string DeleteFileByApplicationID(string companycode, string systemcode, string modelcode, string applicationid) {
            return base.Channel.DeleteFileByApplicationID(companycode, systemcode, modelcode, applicationid);
        }
        
        public string DeleteFileByModelCode(string companycode, string systemcode, string modelcode) {
            return base.Channel.DeleteFileByModelCode(companycode, systemcode, modelcode);
        }
        
        public string DeleteFileBySystemCode(string companycode, string systemcode) {
            return base.Channel.DeleteFileBySystemCode(companycode, systemcode);
        }
        
        public string DeleteFileByCompanycode(string companycode) {
            return base.Channel.DeleteFileByCompanycode(companycode);
        }
        
        public string DeleteFileByOnlyApplicationID(string applicationid) {
            return base.Channel.DeleteFileByOnlyApplicationID(applicationid);
        }
        
        public string DeleteFileByApplicationIDAndFileName(string applicationid, string FileName) {
            return base.Channel.DeleteFileByApplicationIDAndFileName(applicationid, FileName);
        }
        
        public string CreateCompanyDirectory(string companyID, string companyName, string companyCode) {
            return base.Channel.CreateCompanyDirectory(companyID, companyName, companyCode);
        }
    }
}
