CREATE SEQUENCE ACTIVITY_INSTANCE_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE ACTIVITY_STATUS_EVENT_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE TRACKING_DATA_ITEM_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE TRACKING_PROFILE_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE TYPE_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE USER_EVENT_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE WORKFLOW_INSTANCE_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE WORKFLOW_INSTANCE_EVENT_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
