DROP TABLE IF EXISTS INSTANCE_STATE;
CREATE TABLE INSTANCE_STATE
(
  INSTANCE_ID CHAR(36) NOT NULL,
  STATE BLOB,
  STATUS INTEGER UNSIGNED NOT NULL,
  UNLOCKED BOOLEAN NOT NULL,
  BLOCKED BOOLEAN NOT NULL,
  INFO TEXT,
  MODIFIED DATETIME NOT NULL,
  OWNER_ID CHAR(36),
  OWNED_UNTIL DATETIME,
  NEXT_TIMER DATETIME,
  PRIMARY KEY (INSTANCE_ID)
);

CREATE INDEX INSTANCE_STATE_IDX01 ON INSTANCE_STATE (NEXT_TIMER, STATUS, UNLOCKED);
CREATE INDEX INSTANCE_STATE_IDX02 ON INSTANCE_STATE (OWNED_UNTIL, OWNER_ID);