//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.AttendanceLogs.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_flow_definedetail
    {
        public string FLOWDEFINEID { get; set; }
        public string POINTNAME { get; set; }
        public string POINTID { get; set; }
        public string FATHERID { get; set; }
        public string ISSTARTPOINT { get; set; }
        public string ISENDPOINT { get; set; }
        public string ISCOMMONAUDITPOINT { get; set; }
        public string AUDITTYPE { get; set; }
        public string AUDITPOSTID { get; set; }
        public string AUDITROLEID { get; set; }
        public string AUDITROLENAME { get; set; }
        public string AUDITPOSTNAME { get; set; }
        public string OWNERCOMPANY { get; set; }
        public string POINTTYPE { get; set; }
        public Nullable<float> POINTX { get; set; }
        public Nullable<float> POINTY { get; set; }
        public string EFFECTDEHORUS { get; set; }
        public string ISKPIPOINT { get; set; }
    }
}
