ALTER TABLE ACTIVITY_INSTANCE
ADD CONSTRAINT FK_ACT_INST_WF_INST
FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_INSTANCE (WORKFLOW_INSTANCE_ID);

ALTER TABLE ACTIVITY_INSTANCE
ADD CONSTRAINT FK_ACT_INST_WF_INST_EVT
FOREIGN KEY (WORKFLOW_INSTANCE_EVENT_ID) REFERENCES WORKFLOW_INSTANCE_EVENT (WORKFLOW_INSTANCE_EVENT_ID);
