ALTER TABLE ACTIVITY_STATUS_EVENT
ADD CONSTRAINT FK_ACT_STATUS_EVT_WF_INST
FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_INSTANCE (WORKFLOW_INSTANCE_ID);

ALTER TABLE ACTIVITY_STATUS_EVENT
ADD CONSTRAINT FK_ACT_STATUS_EVT_ACT_INST
FOREIGN KEY (ACTIVITY_INSTANCE_ID) REFERENCES ACTIVITY_INSTANCE (ACTIVITY_INSTANCE_ID);

ALTER TABLE ACTIVITY_STATUS_EVENT
ADD CONSTRAINT FK_ACT_STATUS_EVT_ACT_STATUS
FOREIGN KEY (ACTIVITY_STATUS_ID) REFERENCES ACTIVITY_STATUS (ACTIVITY_STATUS_ID);