ALTER TABLE ACTIVITY 
ADD CONSTRAINT FK_ACT_ACT_TYPE
FOREIGN KEY (ACTIVITY_TYPE_ID) REFERENCES TYPE (TYPE_ID);

ALTER TABLE ACTIVITY
ADD CONSTRAINT FK_ACT_WF_TYPE
FOREIGN KEY (WORKFLOW_TYPE_ID) REFERENCES TYPE (TYPE_ID);