 ALTER TABLE ADDED_ACTIVITY
 ADD CONSTRAINT FK_ADDED_ACT_WF_INST
 FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_INSTANCE (WORKFLOW_INSTANCE_ID);
 
 ALTER TABLE ADDED_ACTIVITY
 ADD CONSTRAINT FK_ADDED_ACT_WF_INST_EVT
 FOREIGN KEY (WORKFLOW_INSTANCE_EVENT_ID) REFERENCES WORKFLOW_INSTANCE_EVENT (WORKFLOW_INSTANCE_EVENT_ID);
 
 ALTER TABLE ADDED_ACTIVITY
 ADD CONSTRAINT FK_ADDED_ACT_ACT_TYPE
 FOREIGN KEY (ACTIVITY_TYPE_ID) REFERENCES TYPE (TYPE_ID);