//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.SaaS.BLLCommonServices.WPServicesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseObject", Namespace="http://schemas.datacontract.org/2004/07/SMT.Portal.Communication")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.ResultObject))]
    public partial class BaseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandKey {
            get {
                return this.CommandKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandKeyField, value) != true)) {
                    this.CommandKeyField = value;
                    this.RaisePropertyChanged("CommandKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataContent {
            get {
                return this.DataContentField;
            }
            set {
                if ((object.ReferenceEquals(this.DataContentField, value) != true)) {
                    this.DataContentField = value;
                    this.RaisePropertyChanged("DataContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObject", Namespace="http://schemas.datacontract.org/2004/07/SMT.Portal.Communication")]
    [System.SerializableAttribute()]
    public partial class ResultObject : SMT.SaaS.BLLCommonServices.WPServicesWS.BaseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryExpression", Namespace="SMT.QueryObjects", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class QueryExpression : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement ExpressionXElementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement ExpressionXElement {
            get {
                return this.ExpressionXElementField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionXElementField, value) != true)) {
                    this.ExpressionXElementField = value;
                    this.RaisePropertyChanged("ExpressionXElement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBaseOfanyType", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResultOfanyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.QueryResult))]
    public partial class ResultBaseOfanyType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] InnerResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] InnerResult {
            get {
                return this.InnerResultField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerResultField, value) != true)) {
                    this.InnerResultField = value;
                    this.RaisePropertyChanged("InnerResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResultOfanyType", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResult))]
    public partial class SaveResultOfanyType : SMT.SaaS.BLLCommonServices.WPServicesWS.ResultBaseOfanyType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResultState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResultState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResult", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    [System.SerializableAttribute()]
    public partial class SaveResult : SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResultOfanyType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common.Query")]
    [System.SerializableAttribute()]
    public partial class QueryResult : SMT.SaaS.BLLCommonServices.WPServicesWS.ResultBaseOfanyType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMT.SaaS.BLLCommonServices.WPServicesWS.ResultState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SaaS.BLLCommonServices.WPServicesWS.ResultState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultState", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    public enum ResultState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeOut = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResultState", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    public enum SaveResultState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBaseOfArrayOfanyTypeuHEDJ7Dj", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveExpression))]
    public partial class ResultBaseOfArrayOfanyTypeuHEDJ7Dj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] InnerResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] InnerResult {
            get {
                return this.InnerResultField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerResultField, value) != true)) {
                    this.InnerResultField = value;
                    this.RaisePropertyChanged("InnerResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveExpression", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    [System.SerializableAttribute()]
    public partial class SaveExpression : SMT.SaaS.BLLCommonServices.WPServicesWS.ResultBaseOfArrayOfanyTypeuHEDJ7Dj {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMT.SaaS.BLLCommonServices.WPServicesWS.SaveAction ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SaaS.BLLCommonServices.WPServicesWS.SaveAction Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveAction", Namespace="http://schemas.datacontract.org/2004/07/SMT.SaaS.Common")]
    public enum SaveAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Save = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaveAndSumbit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audit = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_FB_SUBJECT", Namespace="http://schemas.datacontract.org/2004/07/SMT.Portal.Model")]
    [System.SerializableAttribute()]
    public partial class T_FB_SUBJECT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ACTIVEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CHECKSTATESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATECOMPANYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATECOMPANYNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATEDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEDEPARTMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEDEPARTMENTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEPOSTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEPOSTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEUSERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEUSERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EDITSTATESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERCOMPANYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERCOMPANYNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERDEPARTMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERDEPARTMENTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERPOSTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERPOSTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARENTSUBJECTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJECTCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJECTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJECTNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUBJECTTYPEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UPDATEDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATEUSERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATEUSERNAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ACTIVED {
            get {
                return this.ACTIVEDField;
            }
            set {
                if ((this.ACTIVEDField.Equals(value) != true)) {
                    this.ACTIVEDField = value;
                    this.RaisePropertyChanged("ACTIVED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CHECKSTATES {
            get {
                return this.CHECKSTATESField;
            }
            set {
                if ((this.CHECKSTATESField.Equals(value) != true)) {
                    this.CHECKSTATESField = value;
                    this.RaisePropertyChanged("CHECKSTATES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATECOMPANYID {
            get {
                return this.CREATECOMPANYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATECOMPANYIDField, value) != true)) {
                    this.CREATECOMPANYIDField = value;
                    this.RaisePropertyChanged("CREATECOMPANYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATECOMPANYNAME {
            get {
                return this.CREATECOMPANYNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATECOMPANYNAMEField, value) != true)) {
                    this.CREATECOMPANYNAMEField = value;
                    this.RaisePropertyChanged("CREATECOMPANYNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATEDATE {
            get {
                return this.CREATEDATEField;
            }
            set {
                if ((this.CREATEDATEField.Equals(value) != true)) {
                    this.CREATEDATEField = value;
                    this.RaisePropertyChanged("CREATEDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEDEPARTMENTID {
            get {
                return this.CREATEDEPARTMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEDEPARTMENTIDField, value) != true)) {
                    this.CREATEDEPARTMENTIDField = value;
                    this.RaisePropertyChanged("CREATEDEPARTMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEDEPARTMENTNAME {
            get {
                return this.CREATEDEPARTMENTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEDEPARTMENTNAMEField, value) != true)) {
                    this.CREATEDEPARTMENTNAMEField = value;
                    this.RaisePropertyChanged("CREATEDEPARTMENTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEPOSTID {
            get {
                return this.CREATEPOSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEPOSTIDField, value) != true)) {
                    this.CREATEPOSTIDField = value;
                    this.RaisePropertyChanged("CREATEPOSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEPOSTNAME {
            get {
                return this.CREATEPOSTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEPOSTNAMEField, value) != true)) {
                    this.CREATEPOSTNAMEField = value;
                    this.RaisePropertyChanged("CREATEPOSTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEUSERID {
            get {
                return this.CREATEUSERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEUSERIDField, value) != true)) {
                    this.CREATEUSERIDField = value;
                    this.RaisePropertyChanged("CREATEUSERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEUSERNAME {
            get {
                return this.CREATEUSERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEUSERNAMEField, value) != true)) {
                    this.CREATEUSERNAMEField = value;
                    this.RaisePropertyChanged("CREATEUSERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EDITSTATES {
            get {
                return this.EDITSTATESField;
            }
            set {
                if ((this.EDITSTATESField.Equals(value) != true)) {
                    this.EDITSTATESField = value;
                    this.RaisePropertyChanged("EDITSTATES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERCOMPANYID {
            get {
                return this.OWNERCOMPANYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERCOMPANYIDField, value) != true)) {
                    this.OWNERCOMPANYIDField = value;
                    this.RaisePropertyChanged("OWNERCOMPANYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERCOMPANYNAME {
            get {
                return this.OWNERCOMPANYNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERCOMPANYNAMEField, value) != true)) {
                    this.OWNERCOMPANYNAMEField = value;
                    this.RaisePropertyChanged("OWNERCOMPANYNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERDEPARTMENTID {
            get {
                return this.OWNERDEPARTMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERDEPARTMENTIDField, value) != true)) {
                    this.OWNERDEPARTMENTIDField = value;
                    this.RaisePropertyChanged("OWNERDEPARTMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERDEPARTMENTNAME {
            get {
                return this.OWNERDEPARTMENTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERDEPARTMENTNAMEField, value) != true)) {
                    this.OWNERDEPARTMENTNAMEField = value;
                    this.RaisePropertyChanged("OWNERDEPARTMENTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERID {
            get {
                return this.OWNERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERIDField, value) != true)) {
                    this.OWNERIDField = value;
                    this.RaisePropertyChanged("OWNERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERNAME {
            get {
                return this.OWNERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERNAMEField, value) != true)) {
                    this.OWNERNAMEField = value;
                    this.RaisePropertyChanged("OWNERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERPOSTID {
            get {
                return this.OWNERPOSTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERPOSTIDField, value) != true)) {
                    this.OWNERPOSTIDField = value;
                    this.RaisePropertyChanged("OWNERPOSTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNERPOSTNAME {
            get {
                return this.OWNERPOSTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERPOSTNAMEField, value) != true)) {
                    this.OWNERPOSTNAMEField = value;
                    this.RaisePropertyChanged("OWNERPOSTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARENTSUBJECTID {
            get {
                return this.PARENTSUBJECTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PARENTSUBJECTIDField, value) != true)) {
                    this.PARENTSUBJECTIDField = value;
                    this.RaisePropertyChanged("PARENTSUBJECTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUBJECTCODE {
            get {
                return this.SUBJECTCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJECTCODEField, value) != true)) {
                    this.SUBJECTCODEField = value;
                    this.RaisePropertyChanged("SUBJECTCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUBJECTID {
            get {
                return this.SUBJECTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJECTIDField, value) != true)) {
                    this.SUBJECTIDField = value;
                    this.RaisePropertyChanged("SUBJECTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUBJECTNAME {
            get {
                return this.SUBJECTNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJECTNAMEField, value) != true)) {
                    this.SUBJECTNAMEField = value;
                    this.RaisePropertyChanged("SUBJECTNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUBJECTTYPEID {
            get {
                return this.SUBJECTTYPEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SUBJECTTYPEIDField, value) != true)) {
                    this.SUBJECTTYPEIDField = value;
                    this.RaisePropertyChanged("SUBJECTTYPEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UPDATEDATE {
            get {
                return this.UPDATEDATEField;
            }
            set {
                if ((this.UPDATEDATEField.Equals(value) != true)) {
                    this.UPDATEDATEField = value;
                    this.RaisePropertyChanged("UPDATEDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATEUSERID {
            get {
                return this.UPDATEUSERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATEUSERIDField, value) != true)) {
                    this.UPDATEUSERIDField = value;
                    this.RaisePropertyChanged("UPDATEUSERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATEUSERNAME {
            get {
                return this.UPDATEUSERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATEUSERNAMEField, value) != true)) {
                    this.UPDATEUSERNAMEField = value;
                    this.RaisePropertyChanged("UPDATEUSERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WPServicesWS.IApplicationService")]
    public interface IApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IApplicationService/CallApplicationService")]
        void CallApplicationService(string strXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/CallWaitAppService", ReplyAction="http://tempuri.org/IApplicationService/CallWaitAppServiceResponse")]
        string CallWaitAppService(string strXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationServiceChannel : SMT.SaaS.BLLCommonServices.WPServicesWS.IApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServiceClient : System.ServiceModel.ClientBase<SMT.SaaS.BLLCommonServices.WPServicesWS.IApplicationService>, SMT.SaaS.BLLCommonServices.WPServicesWS.IApplicationService {
        
        public ApplicationServiceClient() {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CallApplicationService(string strXml) {
            base.Channel.CallApplicationService(strXml);
        }
        
        public string CallWaitAppService(string strXml) {
            return base.Channel.CallWaitAppService(strXml);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WPServicesWS.IEventTriggerProcess")]
    public interface IEventTriggerProcess {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEventTriggerProcess/EventTriggerProcess")]
        void EventTriggerProcess(string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventTriggerProcessChannel : SMT.SaaS.BLLCommonServices.WPServicesWS.IEventTriggerProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventTriggerProcessClient : System.ServiceModel.ClientBase<SMT.SaaS.BLLCommonServices.WPServicesWS.IEventTriggerProcess>, SMT.SaaS.BLLCommonServices.WPServicesWS.IEventTriggerProcess {
        
        public EventTriggerProcessClient() {
        }
        
        public EventTriggerProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventTriggerProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventTriggerProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventTriggerProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EventTriggerProcess(string param) {
            base.Channel.EventTriggerProcess(param);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WPServicesWS.IWPServices")]
    public interface IWPServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/Execute", ReplyAction="http://tempuri.org/IWPServices/ExecuteResponse")]
        SMT.SaaS.BLLCommonServices.WPServicesWS.ResultObject Execute(SMT.SaaS.BLLCommonServices.WPServicesWS.BaseObject baseObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/UpdateCheckState", ReplyAction="http://tempuri.org/IWPServices/UpdateCheckStateResponse")]
        int UpdateCheckState(string EntityType, string EntityKey, string EntityId, int CheckStates, string strXmlParams, ref string strOutMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/Query", ReplyAction="http://tempuri.org/IWPServices/QueryResponse")]
        SMT.SaaS.BLLCommonServices.WPServicesWS.QueryResult Query(SMT.SaaS.BLLCommonServices.WPServicesWS.QueryExpression expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/Save", ReplyAction="http://tempuri.org/IWPServices/SaveResponse")]
        SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResult Save(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveExpression expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/ListSubject", ReplyAction="http://tempuri.org/IWPServices/ListSubjectResponse")]
        SMT.SaaS.BLLCommonServices.WPServicesWS.T_FB_SUBJECT[] ListSubject(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWPServices/ListSubjects", ReplyAction="http://tempuri.org/IWPServices/ListSubjectsResponse")]
        SMT.SaaS.BLLCommonServices.WPServicesWS.T_FB_SUBJECT[] ListSubjects(string strID, bool IsNew);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWPServicesChannel : SMT.SaaS.BLLCommonServices.WPServicesWS.IWPServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WPServicesClient : System.ServiceModel.ClientBase<SMT.SaaS.BLLCommonServices.WPServicesWS.IWPServices>, SMT.SaaS.BLLCommonServices.WPServicesWS.IWPServices {
        
        public WPServicesClient() {
        }
        
        public WPServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WPServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WPServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WPServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMT.SaaS.BLLCommonServices.WPServicesWS.ResultObject Execute(SMT.SaaS.BLLCommonServices.WPServicesWS.BaseObject baseObject) {
            return base.Channel.Execute(baseObject);
        }
        
        public int UpdateCheckState(string EntityType, string EntityKey, string EntityId, int CheckStates, string strXmlParams, ref string strOutMsg) {
            return base.Channel.UpdateCheckState(EntityType, EntityKey, EntityId, CheckStates, strXmlParams, ref strOutMsg);
        }
        
        public SMT.SaaS.BLLCommonServices.WPServicesWS.QueryResult Query(SMT.SaaS.BLLCommonServices.WPServicesWS.QueryExpression expression) {
            return base.Channel.Query(expression);
        }
        
        public SMT.SaaS.BLLCommonServices.WPServicesWS.SaveResult Save(SMT.SaaS.BLLCommonServices.WPServicesWS.SaveExpression expression) {
            return base.Channel.Save(expression);
        }
        
        public SMT.SaaS.BLLCommonServices.WPServicesWS.T_FB_SUBJECT[] ListSubject(string strID) {
            return base.Channel.ListSubject(strID);
        }
        
        public SMT.SaaS.BLLCommonServices.WPServicesWS.T_FB_SUBJECT[] ListSubjects(string strID, bool IsNew) {
            return base.Channel.ListSubjects(strID, IsNew);
        }
    }
}
