ALTER TABLE TRACKING_DATA_ITEM
ADD CONSTRAINT FK_TRK_DT_ITM_WF_INST
FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_INSTANCE (WORKFLOW_INSTANCE_ID); 

ALTER TABLE TRACKING_DATA_ITEM
ADD CONSTRAINT FK_TRK_DT_ITM_FIELD_TYPE
FOREIGN KEY (FIELD_TYPE_ID) REFERENCES TYPE (TYPE_ID); 