ALTER TABLE WORKFLOW_INSTANCE_EVENT
ADD CONSTRAINT FK_WF_INST_EVT_WF_INST
FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_INSTANCE (WORKFLOW_INSTANCE_ID);

ALTER TABLE WORKFLOW_INSTANCE_EVENT
ADD CONSTRAINT FK_WF_INST_EVT_WF_INST_STATUS
FOREIGN KEY (WORKFLOW_INSTANCE_STATUS_ID) REFERENCES WORKFLOW_INSTANCE_STATUS (WORKFLOW_INSTANCE_STATUS_ID);

ALTER TABLE WORKFLOW_INSTANCE_EVENT
ADD CONSTRAINT FK_WF_INST_EVT_EVT_ARG_TYPE
FOREIGN KEY (EVENT_ARG_TYPE_ID) REFERENCES TYPE (TYPE_ID);