//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.SaaS.OA.UI.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OASystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OASystem() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMT.SaaS.OA.UI.Assets.Resources.OASystem", typeof(OASystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 附件信息 的本地化字符串。
        /// </summary>
        public static string ACCESSORYINFO {
            get {
                return ResourceManager.GetString("ACCESSORYINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件上传时间 的本地化字符串。
        /// </summary>
        public static string ACCESSORYUPLOADTIME {
            get {
                return ResourceManager.GetString("ACCESSORYUPLOADTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行账号 的本地化字符串。
        /// </summary>
        public static string ACCOUNTCODE {
            get {
                return ResourceManager.GetString("ACCOUNTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加并提交审核 的本地化字符串。
        /// </summary>
        public static string ADDANDAUDITING {
            get {
                return ResourceManager.GetString("ADDANDAUDITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增档案 的本地化字符串。
        /// </summary>
        public static string ADDARCHIVE {
            get {
                return ResourceManager.GetString("ADDARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增外借 的本地化字符串。
        /// </summary>
        public static string ADDBORROW {
            get {
                return ResourceManager.GetString("ADDBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string ADDBUTTON {
            get {
                return ResourceManager.GetString("ADDBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间 的本地化字符串。
        /// </summary>
        public static string ADDDATE {
            get {
                return ResourceManager.GetString("ADDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增证照 的本地化字符串。
        /// </summary>
        public static string ADDLICENSE {
            get {
                return ResourceManager.GetString("ADDLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加会议室信息 的本地化字符串。
        /// </summary>
        public static string ADDMEETINGROOMINFORMATION {
            get {
                return ResourceManager.GetString("ADDMEETINGROOMINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加不提交审核 的本地化字符串。
        /// </summary>
        public static string ADDNOTAUDITING {
            get {
                return ResourceManager.GetString("ADDNOTAUDITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增机构 的本地化字符串。
        /// </summary>
        public static string ADDORGAN {
            get {
                return ResourceManager.GetString("ADDORGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加人 的本地化字符串。
        /// </summary>
        public static string ADDPEOPLE {
            get {
                return ResourceManager.GetString("ADDPEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        public static string ADDSUCCESSED {
            get {
                return ResourceManager.GetString("ADDSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加模板 的本地化字符串。
        /// </summary>
        public static string ADDTEMPLATE {
            get {
                return ResourceManager.GetString("ADDTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请状态 的本地化字符串。
        /// </summary>
        public static string APPLICATIONSTATE {
            get {
                return ResourceManager.GetString("APPLICATIONSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string APPOVALBUTTON {
            get {
                return ResourceManager.GetString("APPOVALBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批档案 的本地化字符串。
        /// </summary>
        public static string APPROVALARCHIVE {
            get {
                return ResourceManager.GetString("APPROVALARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批外借 的本地化字符串。
        /// </summary>
        public static string APPROVALBORROW {
            get {
                return ResourceManager.GetString("APPROVALBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批机构 的本地化字符串。
        /// </summary>
        public static string APPROVALORGAN {
            get {
                return ResourceManager.GetString("APPROVALORGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批通过 的本地化字符串。
        /// </summary>
        public static string APPROVED {
            get {
                return ResourceManager.GetString("APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批中 的本地化字符串。
        /// </summary>
        public static string APPROVING {
            get {
                return ResourceManager.GetString("APPROVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核状态 的本地化字符串。
        /// </summary>
        public static string APPROVSTATE {
            get {
                return ResourceManager.GetString("APPROVSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档案内容 的本地化字符串。
        /// </summary>
        public static string ARCHIVESCONTENT {
            get {
                return ResourceManager.GetString("ARCHIVESCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档案标题 的本地化字符串。
        /// </summary>
        public static string ARCHIVESTITLE {
            get {
                return ResourceManager.GetString("ARCHIVESTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档案类型 的本地化字符串。
        /// </summary>
        public static string ARCHIVESTYPE {
            get {
                return ResourceManager.GetString("ARCHIVESTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审核会议 的本地化字符串。
        /// </summary>
        public static string AUDITEDMEETING {
            get {
                return ResourceManager.GetString("AUDITEDMEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核未通过 的本地化字符串。
        /// </summary>
        public static string AUDITINGDEFEATED {
            get {
                return ResourceManager.GetString("AUDITINGDEFEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功审核！ 的本地化字符串。
        /// </summary>
        public static string AUDITSUCCESSED {
            get {
                return ResourceManager.GetString("AUDITSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行帐号 的本地化字符串。
        /// </summary>
        public static string BANKCARDNUMBER {
            get {
                return ResourceManager.GetString("BANKCARDNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开户银行代码 的本地化字符串。
        /// </summary>
        public static string BANKID {
            get {
                return ResourceManager.GetString("BANKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行名称 的本地化字符串。
        /// </summary>
        public static string BANKNAME {
            get {
                return ResourceManager.GetString("BANKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BASEINFO {
            get {
                return ResourceManager.GetString("BASEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期 的本地化字符串。
        /// </summary>
        public static string BDAY {
            get {
                return ResourceManager.GetString("BDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生年月 的本地化字符串。
        /// </summary>
        public static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血型 的本地化字符串。
        /// </summary>
        public static string BLOODTYPE {
            get {
                return ResourceManager.GetString("BLOODTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大楼名称 的本地化字符串。
        /// </summary>
        public static string BUILDING {
            get {
                return ResourceManager.GetString("BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 办公地址 的本地化字符串。
        /// </summary>
        public static string BUSINESSADDRESS {
            get {
                return ResourceManager.GetString("BUSINESSADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经营范围 的本地化字符串。
        /// </summary>
        public static string BUSINESSSCOPE {
            get {
                return ResourceManager.GetString("BUSINESSSCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营业执照号 的本地化字符串。
        /// </summary>
        public static string BUSSINESSLICENCENO {
            get {
                return ResourceManager.GetString("BUSSINESSLICENCENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤消 的本地化字符串。
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CANCELBUTTON {
            get {
                return ResourceManager.GetString("CANCELBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认撤消当前记录吗！ 的本地化字符串。
        /// </summary>
        public static string CANCELCONFIRM {
            get {
                return ResourceManager.GetString("CANCELCONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤消成功！ 的本地化字符串。
        /// </summary>
        public static string CANCELLEDSUCCESSED {
            get {
                return ResourceManager.GetString("CANCELLEDSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订餐 的本地化字符串。
        /// </summary>
        public static string CANCELORDERMEAL {
            get {
                return ResourceManager.GetString("CANCELORDERMEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出租标志 的本地化字符串。
        /// </summary>
        public static string CANRENT {
            get {
                return ResourceManager.GetString("CANRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮换岗位 的本地化字符串。
        /// </summary>
        public static string CHANGEPOST {
            get {
                return ResourceManager.GetString("CHANGEPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string CHECKALL {
            get {
                return ResourceManager.GetString("CHECKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退房日期 的本地化字符串。
        /// </summary>
        public static string CHECKOUTDATE {
            get {
                return ResourceManager.GetString("CHECKOUTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核状态 的本地化字符串。
        /// </summary>
        public static string CHECKSTATE {
            get {
                return ResourceManager.GetString("CHECKSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核人 的本地化字符串。
        /// </summary>
        public static string CHECKUSER {
            get {
                return ResourceManager.GetString("CHECKUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子女 的本地化字符串。
        /// </summary>
        public static string CHILDREN {
            get {
                return ResourceManager.GetString("CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择档案 的本地化字符串。
        /// </summary>
        public static string CHOOSEARCHIVE {
            get {
                return ResourceManager.GetString("CHOOSEARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择证照 的本地化字符串。
        /// </summary>
        public static string CHOOSELICENSE {
            get {
                return ResourceManager.GetString("CHOOSELICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司中文名 的本地化字符串。
        /// </summary>
        public static string CNAME {
            get {
                return ResourceManager.GetString("CNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批意见 的本地化字符串。
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小区名称 的本地化字符串。
        /// </summary>
        public static string COMMUNITY {
            get {
                return ResourceManager.GetString("COMMUNITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司编号 的本地化字符串。
        /// </summary>
        public static string COMPANRYCODE {
            get {
                return ResourceManager.GetString("COMPANRYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司地址 的本地化字符串。
        /// </summary>
        public static string COMPANYADDRESS {
            get {
                return ResourceManager.GetString("COMPANYADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司类型 的本地化字符串。
        /// </summary>
        public static string COMPANYCATEGORY {
            get {
                return ResourceManager.GetString("COMPANYCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司级别 的本地化字符串。
        /// </summary>
        public static string COMPANYLEVEL {
            get {
                return ResourceManager.GetString("COMPANYLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string COMPANYNAME {
            get {
                return ResourceManager.GetString("COMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲属公司地址 的本地化字符串。
        /// </summary>
        public static string COMRELATIONINFO {
            get {
                return ResourceManager.GetString("COMRELATIONINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string CONFIRMBUTTON {
            get {
                return ResourceManager.GetString("CONFIRMBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认信息 的本地化字符串。
        /// </summary>
        public static string CONFIRMINFO {
            get {
                return ResourceManager.GetString("CONFIRMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容上传时间 的本地化字符串。
        /// </summary>
        public static string CONTENTUPLOADTME {
            get {
                return ResourceManager.GetString("CONTENTUPLOADTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CREATEDATE {
            get {
                return ResourceManager.GetString("CREATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string CREATEUSERID {
            get {
                return ResourceManager.GetString("CREATEUSERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string CURRENTADRESS {
            get {
                return ResourceManager.GetString("CURRENTADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行卡号 的本地化字符串。
        /// </summary>
        public static string DEBITVISACARDNO {
            get {
                return ResourceManager.GetString("DEBITVISACARDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DELBUTTON {
            get {
                return ResourceManager.GetString("DELBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除当前行吗？ 的本地化字符串。
        /// </summary>
        public static string DELETEALTER {
            get {
                return ResourceManager.GetString("DELETEALTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除档案 的本地化字符串。
        /// </summary>
        public static string DELETEARCHIVE {
            get {
                return ResourceManager.GetString("DELETEARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除外借 的本地化字符串。
        /// </summary>
        public static string DELETEBORROW {
            get {
                return ResourceManager.GetString("DELETEBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除确认 的本地化字符串。
        /// </summary>
        public static string DELETECONFIRM {
            get {
                return ResourceManager.GetString("DELETECONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除证照 的本地化字符串。
        /// </summary>
        public static string DELETELICENSE {
            get {
                return ResourceManager.GetString("DELETELICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除机构 的本地化字符串。
        /// </summary>
        public static string DELETEORGAN {
            get {
                return ResourceManager.GetString("DELETEORGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        public static string DELETESUCCESSED {
            get {
                return ResourceManager.GetString("DELETESUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门编号 的本地化字符串。
        /// </summary>
        public static string DEPARTMENTCODE {
            get {
                return ResourceManager.GetString("DEPARTMENTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门字典 的本地化字符串。
        /// </summary>
        public static string DEPARTMENTDICT {
            get {
                return ResourceManager.GetString("DEPARTMENTDICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门职责 的本地化字符串。
        /// </summary>
        public static string DEPARTMENTFUNCTION {
            get {
                return ResourceManager.GetString("DEPARTMENTFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门级别 的本地化字符串。
        /// </summary>
        public static string DEPARTMENTLEVEL {
            get {
                return ResourceManager.GetString("DEPARTMENTLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称 的本地化字符串。
        /// </summary>
        public static string DEPARTMENTNAME {
            get {
                return ResourceManager.GetString("DEPARTMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 押金 的本地化字符串。
        /// </summary>
        public static string DEPOSIT {
            get {
                return ResourceManager.GetString("DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string DETAILINFO {
            get {
                return ResourceManager.GetString("DETAILINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统数据字典 的本地化字符串。
        /// </summary>
        public static string DICTIONARY {
            get {
                return ResourceManager.GetString("DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典名称 的本地化字符串。
        /// </summary>
        public static string DICTIONARYNAME {
            get {
                return ResourceManager.GetString("DICTIONARYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典值 的本地化字符串。
        /// </summary>
        public static string DICTIONARYVALUE {
            get {
                return ResourceManager.GetString("DICTIONARYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典类型名 的本地化字符串。
        /// </summary>
        public static string DICTIONCATEGORY {
            get {
                return ResourceManager.GetString("DICTIONCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料类型 的本地化字符串。
        /// </summary>
        public static string DOCTYPE {
            get {
                return ResourceManager.GetString("DOCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档类型 的本地化字符串。
        /// </summary>
        public static string DOCUMENTTYPE {
            get {
                return ResourceManager.GetString("DOCUMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿箱 的本地化字符串。
        /// </summary>
        public static string DRAFTBOX {
            get {
                return ResourceManager.GetString("DRAFTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改档案 的本地化字符串。
        /// </summary>
        public static string EDITARCHIVE {
            get {
                return ResourceManager.GetString("EDITARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改外借 的本地化字符串。
        /// </summary>
        public static string EDITBORROW {
            get {
                return ResourceManager.GetString("EDITBORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改证照 的本地化字符串。
        /// </summary>
        public static string EDITLICENSE {
            get {
                return ResourceManager.GetString("EDITLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改机构 的本地化字符串。
        /// </summary>
        public static string EDITORGAN {
            get {
                return ResourceManager.GetString("EDITORGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改原因 的本地化字符串。
        /// </summary>
        public static string EDITREASON {
            get {
                return ResourceManager.GetString("EDITREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string EDITSTATE {
            get {
                return ResourceManager.GetString("EDITSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教育记录 的本地化字符串。
        /// </summary>
        public static string EDUCATEHISTORY {
            get {
                return ResourceManager.GetString("EDUCATEHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮箱 的本地化字符串。
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工编号 的本地化字符串。
        /// </summary>
        public static string EMPLOYEECODE {
            get {
                return ResourceManager.GetString("EMPLOYEECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工姓名 的本地化字符串。
        /// </summary>
        public static string EMPLOYEENAME {
            get {
                return ResourceManager.GetString("EMPLOYEENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工性别 的本地化字符串。
        /// </summary>
        public static string EMPLOYEESEX {
            get {
                return ResourceManager.GetString("EMPLOYEESEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工状态 的本地化字符串。
        /// </summary>
        public static string EMPLOYEESTATE {
            get {
                return ResourceManager.GetString("EMPLOYEESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司英文名 的本地化字符串。
        /// </summary>
        public static string ENAME {
            get {
                return ResourceManager.GetString("ENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到期日期 的本地化字符串。
        /// </summary>
        public static string ENDDATE {
            get {
                return ResourceManager.GetString("ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string ENDTIME {
            get {
                return ResourceManager.GetString("ENDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语水平 的本地化字符串。
        /// </summary>
        public static string ENGLISHLEVEL {
            get {
                return ResourceManager.GetString("ENGLISHLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期望薪资 的本地化字符串。
        /// </summary>
        public static string EXPECTATIONSALARY {
            get {
                return ResourceManager.GetString("EXPECTATIONSALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预计归还时间 的本地化字符串。
        /// </summary>
        public static string EXPECTEDRETURNTIME {
            get {
                return ResourceManager.GetString("EXPECTEDRETURNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作经历 的本地化字符串。
        /// </summary>
        public static string EXPERIENCE {
            get {
                return ResourceManager.GetString("EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证照编号 的本地化字符串。
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家庭详细地址 的本地化字符串。
        /// </summary>
        public static string FAMILYADDRESS {
            get {
                return ResourceManager.GetString("FAMILYADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家庭电话 的本地化字符串。
        /// </summary>
        public static string FAMILYPHONE {
            get {
                return ResourceManager.GetString("FAMILYPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家庭邮政编码 的本地化字符串。
        /// </summary>
        public static string FAMILYPOSTCODE {
            get {
                return ResourceManager.GetString("FAMILYPOSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家庭邮证编码 的本地化字符串。
        /// </summary>
        public static string FAMILYZIPCODE {
            get {
                return ResourceManager.GetString("FAMILYZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接上级 的本地化字符串。
        /// </summary>
        public static string FATHERPOSTID {
            get {
                return ResourceManager.GetString("FATHERPOSTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        public static string FAXNUMBER {
            get {
                return ResourceManager.GetString("FAXNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指纹编号 的本地化字符串。
        /// </summary>
        public static string FINGERPRINTID {
            get {
                return ResourceManager.GetString("FINGERPRINTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楼层 的本地化字符串。
        /// </summary>
        public static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级别 的本地化字符串。
        /// </summary>
        public static string GRADENAME {
            get {
                return ResourceManager.GetString("GRADENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毕业学校 的本地化字符串。
        /// </summary>
        public static string GRADUATESCHOOL {
            get {
                return ResourceManager.GetString("GRADUATESCHOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有无子女 的本地化字符串。
        /// </summary>
        public static string HASCHILDREN {
            get {
                return ResourceManager.GetString("HASCHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否归还 的本地化字符串。
        /// </summary>
        public static string HASRETURN {
            get {
                return ResourceManager.GetString("HASRETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有亲属 的本地化字符串。
        /// </summary>
        public static string HAVECOMRELATION {
            get {
                return ResourceManager.GetString("HAVECOMRELATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身高 的本地化字符串。
        /// </summary>
        public static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租房人 的本地化字符串。
        /// </summary>
        public static string HIREER {
            get {
                return ResourceManager.GetString("HIREER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号码 的本地化字符串。
        /// </summary>
        public static string IDCARDNUMBER {
            get {
                return ResourceManager.GetString("IDCARDNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证件号码 的本地化字符串。
        /// </summary>
        public static string IDNUMBER {
            get {
                return ResourceManager.GetString("IDNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证件类型 的本地化字符串。
        /// </summary>
        public static string IDTYPE {
            get {
                return ResourceManager.GetString("IDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否存档 的本地化字符串。
        /// </summary>
        public static string ISARCHIVES {
            get {
                return ResourceManager.GetString("ISARCHIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否取消 的本地化字符串。
        /// </summary>
        public static string ISCANCEL {
            get {
                return ResourceManager.GetString("ISCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作描述 的本地化字符串。
        /// </summary>
        public static string JOBDESCRIPTION {
            get {
                return ResourceManager.GetString("JOBDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参会 的本地化字符串。
        /// </summary>
        public static string JOINMEETING {
            get {
                return ResourceManager.GetString("JOINMEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租房协议 的本地化字符串。
        /// </summary>
        public static string LEASECONTRACT {
            get {
                return ResourceManager.GetString("LEASECONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法人代表 的本地化字符串。
        /// </summary>
        public static string LEGALPERSON {
            get {
                return ResourceManager.GetString("LEGALPERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法人身份证号 的本地化字符串。
        /// </summary>
        public static string LEGALPERSONID {
            get {
                return ResourceManager.GetString("LEGALPERSONID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借出 的本地化字符串。
        /// </summary>
        public static string LEND {
            get {
                return ResourceManager.GetString("LEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出借人 的本地化字符串。
        /// </summary>
        public static string LENDER {
            get {
                return ResourceManager.GetString("LENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借出标志 的本地化字符串。
        /// </summary>
        public static string LENDFLAG {
            get {
                return ResourceManager.GetString("LENDFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借出时间 的本地化字符串。
        /// </summary>
        public static string LENDTIME {
            get {
                return ResourceManager.GetString("LENDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证照编号 的本地化字符串。
        /// </summary>
        public static string LICENCENO {
            get {
                return ResourceManager.GetString("LICENCENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证照名称 的本地化字符串。
        /// </summary>
        public static string LICENSENAME {
            get {
                return ResourceManager.GetString("LICENSENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string LINKMAN {
            get {
                return ResourceManager.GetString("LINKMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主修课程 的本地化字符串。
        /// </summary>
        public static string MAJORS {
            get {
                return ResourceManager.GetString("MAJORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理费 的本地化字符串。
        /// </summary>
        public static string MANAGEMENTFEE {
            get {
                return ResourceManager.GetString("MANAGEMENTFEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 婚姻状况 的本地化字符串。
        /// </summary>
        public static string MARRIAGE {
            get {
                return ResourceManager.GetString("MARRIAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议内容 的本地化字符串。
        /// </summary>
        public static string MEETINGCONTENT {
            get {
                return ResourceManager.GetString("MEETINGCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参会人员 的本地化字符串。
        /// </summary>
        public static string MEETINGMEMBER {
            get {
                return ResourceManager.GetString("MEETINGMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议室 的本地化字符串。
        /// </summary>
        public static string MEETINGROOM {
            get {
                return ResourceManager.GetString("MEETINGROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议主题 的本地化字符串。
        /// </summary>
        public static string MEETINGTITLE {
            get {
                return ResourceManager.GetString("MEETINGTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议类型 的本地化字符串。
        /// </summary>
        public static string MEETINGTYPE {
            get {
                return ResourceManager.GetString("MEETINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人数 的本地化字符串。
        /// </summary>
        public static string MEMBERCOUNT {
            get {
                return ResourceManager.GetString("MEMBERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string MOBILE {
            get {
                return ResourceManager.GetString("MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        public static string MODIFYSUCCESSED {
            get {
                return ResourceManager.GetString("MODIFYSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的附件 的本地化字符串。
        /// </summary>
        public static string MYACCESSORY {
            get {
                return ResourceManager.GetString("MYACCESSORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的内容 的本地化字符串。
        /// </summary>
        public static string MYMEETINGCONTENT {
            get {
                return ResourceManager.GetString("MYMEETINGCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族 的本地化字符串。
        /// </summary>
        public static string NATION {
            get {
                return ResourceManager.GetString("NATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户昵称 的本地化字符串。
        /// </summary>
        public static string NICKNAME {
            get {
                return ResourceManager.GetString("NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无有效的权限 的本地化字符串。
        /// </summary>
        public static string NOPERMISSION {
            get {
                return ResourceManager.GetString("NOPERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未提交审核 的本地化字符串。
        /// </summary>
        public static string NOSUBMISSIONMEETING {
            get {
                return ResourceManager.GetString("NOSUBMISSIONMEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        public static string NOTALLOWNULL {
            get {
                return ResourceManager.GetString("NOTALLOWNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OKBUTTON {
            get {
                return ResourceManager.GetString("OKBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string OPERATION {
            get {
                return ResourceManager.GetString("OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已订餐 的本地化字符串。
        /// </summary>
        public static string ORDEREDMEAL {
            get {
                return ResourceManager.GetString("ORDEREDMEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待订餐 的本地化字符串。
        /// </summary>
        public static string ORDERINGMEAL {
            get {
                return ResourceManager.GetString("ORDERINGMEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订餐信息 的本地化字符串。
        /// </summary>
        public static string ORDERMEALCONTENT {
            get {
                return ResourceManager.GetString("ORDERMEALCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订餐时间 的本地化字符串。
        /// </summary>
        public static string ORDERMEALDATE {
            get {
                return ResourceManager.GetString("ORDERMEALDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订餐标题 的本地化字符串。
        /// </summary>
        public static string ORDERMEALTITLE {
            get {
                return ResourceManager.GetString("ORDERMEALTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订餐人 的本地化字符串。
        /// </summary>
        public static string ORDERMEALUSER {
            get {
                return ResourceManager.GetString("ORDERMEALUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构代码 的本地化字符串。
        /// </summary>
        public static string ORGANCODE {
            get {
                return ResourceManager.GetString("ORGANCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司字典 的本地化字符串。
        /// </summary>
        public static string ORGANIZATIONDEF {
            get {
                return ResourceManager.GetString("ORGANIZATIONDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构名称 的本地化字符串。
        /// </summary>
        public static string ORGANNAME {
            get {
                return ResourceManager.GetString("ORGANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校外奖励 的本地化字符串。
        /// </summary>
        public static string OUTENCOURAGE {
            get {
                return ResourceManager.GetString("OUTENCOURAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string PHOTO {
            get {
                return ResourceManager.GetString("PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 政治面貌 的本地化字符串。
        /// </summary>
        public static string POLITICS {
            get {
                return ResourceManager.GetString("POLITICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存放位置 的本地化字符串。
        /// </summary>
        public static string POSITION {
            get {
                return ResourceManager.GetString("POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作岗位 的本地化字符串。
        /// </summary>
        public static string POST {
            get {
                return ResourceManager.GetString("POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位编号 的本地化字符串。
        /// </summary>
        public static string POSTCODE {
            get {
                return ResourceManager.GetString("POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位职责 的本地化字符串。
        /// </summary>
        public static string POSTFUNCTION {
            get {
                return ResourceManager.GetString("POSTFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位目标 的本地化字符串。
        /// </summary>
        public static string POSTGOAL {
            get {
                return ResourceManager.GetString("POSTGOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位级别 的本地化字符串。
        /// </summary>
        public static string POSTLEVEL {
            get {
                return ResourceManager.GetString("POSTLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位名称 的本地化字符串。
        /// </summary>
        public static string POSTNAME {
            get {
                return ResourceManager.GetString("POSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员编制 的本地化字符串。
        /// </summary>
        public static string POSTNUMBER {
            get {
                return ResourceManager.GetString("POSTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓急名 的本地化字符串。
        /// </summary>
        public static string PRIORITYNAME {
            get {
                return ResourceManager.GetString("PRIORITYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晋升方向 的本地化字符串。
        /// </summary>
        public static string PROMOTEDIRECTION {
            get {
                return ResourceManager.GetString("PROMOTEDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 籍贯 的本地化字符串。
        /// </summary>
        public static string PROVINCE {
            get {
                return ResourceManager.GetString("PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用途 的本地化字符串。
        /// </summary>
        public static string PURPOSE {
            get {
                return ResourceManager.GetString("PURPOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册费用 的本地化字符串。
        /// </summary>
        public static string REGISTERCHARGE {
            get {
                return ResourceManager.GetString("REGISTERCHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册类型 的本地化字符串。
        /// </summary>
        public static string REGISTERTYPE {
            get {
                return ResourceManager.GetString("REGISTERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 户口所在地 的本地化字符串。
        /// </summary>
        public static string REGRESIDENCE {
            get {
                return ResourceManager.GetString("REGRESIDENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string REMARK {
            get {
                return ResourceManager.GetString("REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒天数 的本地化字符串。
        /// </summary>
        public static string REMINDDAY {
            get {
                return ResourceManager.GetString("REMINDDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租金 的本地化字符串。
        /// </summary>
        public static string RENTAL {
            get {
                return ResourceManager.GetString("RENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简历 的本地化字符串。
        /// </summary>
        public static string RESUME {
            get {
                return ResourceManager.GetString("RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简历ID 的本地化字符串。
        /// </summary>
        public static string RESUMEID {
            get {
                return ResourceManager.GetString("RESUMEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归还 的本地化字符串。
        /// </summary>
        public static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归还档案 的本地化字符串。
        /// </summary>
        public static string RETURNARCHIVE {
            get {
                return ResourceManager.GetString("RETURNARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归还时间 的本地化字符串。
        /// </summary>
        public static string RETURNTIME {
            get {
                return ResourceManager.GetString("RETURNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间编号 的本地化字符串。
        /// </summary>
        public static string ROOMNO {
            get {
                return ResourceManager.GetString("ROOMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月薪 的本地化字符串。
        /// </summary>
        public static string SALARY {
            get {
                return ResourceManager.GetString("SALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 薪资等级 的本地化字符串。
        /// </summary>
        public static string SALARYLEVEL {
            get {
                return ResourceManager.GetString("SALARYLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校内奖励 的本地化字符串。
        /// </summary>
        public static string SCHOOLENCOURAGE {
            get {
                return ResourceManager.GetString("SCHOOLENCOURAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择公司！ 的本地化字符串。
        /// </summary>
        public static string SELECTCOMPANY {
            get {
                return ResourceManager.GetString("SELECTCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择公司类型！ 的本地化字符串。
        /// </summary>
        public static string SELECTCPYCATEGORY {
            get {
                return ResourceManager.GetString("SELECTCPYCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择公司级别！ 的本地化字符串。
        /// </summary>
        public static string SELECTCPYLEVEL {
            get {
                return ResourceManager.GetString("SELECTCPYLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择修改的数据！ 的本地化字符串。
        /// </summary>
        public static string SELECTDATAALERT {
            get {
                return ResourceManager.GetString("SELECTDATAALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择日期 的本地化字符串。
        /// </summary>
        public static string SELECTDATE {
            get {
                return ResourceManager.GetString("SELECTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择部门！ 的本地化字符串。
        /// </summary>
        public static string SELECTDEPART {
            get {
                return ResourceManager.GetString("SELECTDEPART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择部门级别！ 的本地化字符串。
        /// </summary>
        public static string SELECTDEPARTMENTLEVEL {
            get {
                return ResourceManager.GetString("SELECTDEPARTMENTLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择岗位！ 的本地化字符串。
        /// </summary>
        public static string SELECTPOSITION {
            get {
                return ResourceManager.GetString("SELECTPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择岗位级别！ 的本地化字符串。
        /// </summary>
        public static string SELECTPOSITIONLEVEL {
            get {
                return ResourceManager.GetString("SELECTPOSITIONLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自我评价 的本地化字符串。
        /// </summary>
        public static string SELFAPPRAISE {
            get {
                return ResourceManager.GetString("SELFAPPRAISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发文标题 的本地化字符串。
        /// </summary>
        public static string SENDDOCTITLE {
            get {
                return ResourceManager.GetString("SENDDOCTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string SEX {
            get {
                return ResourceManager.GetString("SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所学专业 的本地化字符串。
        /// </summary>
        public static string SPECIALTY {
            get {
                return ResourceManager.GetString("SPECIALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string STARTDATE {
            get {
                return ResourceManager.GetString("STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起止日期 的本地化字符串。
        /// </summary>
        public static string STARTENDDATE {
            get {
                return ResourceManager.GetString("STARTENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string STARTTIME {
            get {
                return ResourceManager.GetString("STARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身高 的本地化字符串。
        /// </summary>
        public static string STATURE {
            get {
                return ResourceManager.GetString("STATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功提交审核！ 的本地化字符串。
        /// </summary>
        public static string SUBMITAUDITSUCCESSED {
            get {
                return ResourceManager.GetString("SUBMITAUDITSUCCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交审核 的本地化字符串。
        /// </summary>
        public static string SUBMITBUTTON {
            get {
                return ResourceManager.GetString("SUBMITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级公司 的本地化字符串。
        /// </summary>
        public static string SUPERIORORG {
            get {
                return ResourceManager.GetString("SUPERIORORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        public static string TELNUMBER {
            get {
                return ResourceManager.GetString("TELNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板内容 的本地化字符串。
        /// </summary>
        public static string TEMPLATECONTENT {
            get {
                return ResourceManager.GetString("TEMPLATECONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string TEMPLATENAME {
            get {
                return ResourceManager.GetString("TEMPLATENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高学历 的本地化字符串。
        /// </summary>
        public static string TIPTOPEDUCATION {
            get {
                return ResourceManager.GetString("TIPTOPEDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批未通过 的本地化字符串。
        /// </summary>
        public static string UNAPPROVED {
            get {
                return ResourceManager.GetString("UNAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管辖人数 的本地化字符串。
        /// </summary>
        public static string UNDERNUMBER {
            get {
                return ResourceManager.GetString("UNDERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审批 的本地化字符串。
        /// </summary>
        public static string UNSUBMIT {
            get {
                return ResourceManager.GetString("UNSUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string UPDATEBUTTON {
            get {
                return ResourceManager.GetString("UPDATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        public static string UPDATEDATE {
            get {
                return ResourceManager.GetString("UPDATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改人 的本地化字符串。
        /// </summary>
        public static string UPDATEUSERID {
            get {
                return ResourceManager.GetString("UPDATEUSERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传附件 的本地化字符串。
        /// </summary>
        public static string UPLOAD {
            get {
                return ResourceManager.GetString("UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传附件 的本地化字符串。
        /// </summary>
        public static string UPLOADACCESSORY {
            get {
                return ResourceManager.GetString("UPLOADACCESSORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传内容 的本地化字符串。
        /// </summary>
        public static string UPLOADCONTENT {
            get {
                return ResourceManager.GetString("UPLOADCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传照片 的本地化字符串。
        /// </summary>
        public static string UPLOADPHOTO {
            get {
                return ResourceManager.GetString("UPLOADPHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急联系方式 的本地化字符串。
        /// </summary>
        public static string URGENCYCONTACT {
            get {
                return ResourceManager.GetString("URGENCYCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急联系人 的本地化字符串。
        /// </summary>
        public static string URGENCYPERSON {
            get {
                return ResourceManager.GetString("URGENCYPERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期从 的本地化字符串。
        /// </summary>
        public static string VALIDPERIODFROM {
            get {
                return ResourceManager.GetString("VALIDPERIODFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期至 的本地化字符串。
        /// </summary>
        public static string VALIDPERIODTO {
            get {
                return ResourceManager.GetString("VALIDPERIODTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看档案 的本地化字符串。
        /// </summary>
        public static string VIEWARCHIVE {
            get {
                return ResourceManager.GetString("VIEWARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审核会议 的本地化字符串。
        /// </summary>
        public static string WAITINGAUDITINGMEETING {
            get {
                return ResourceManager.GetString("WAITINGAUDITINGMEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意向地区 的本地化字符串。
        /// </summary>
        public static string WISHAREA {
            get {
                return ResourceManager.GetString("WISHAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意向公司 的本地化字符串。
        /// </summary>
        public static string WISHCOMPANY {
            get {
                return ResourceManager.GetString("WISHCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意向岗位 的本地化字符串。
        /// </summary>
        public static string WISHPOST {
            get {
                return ResourceManager.GetString("WISHPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社会工龄 的本地化字符串。
        /// </summary>
        public static string WORKINGAGE {
            get {
                return ResourceManager.GetString("WORKINGAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政编码 的本地化字符串。
        /// </summary>
        public static string ZIPCODE {
            get {
                return ResourceManager.GetString("ZIPCODE", resourceCulture);
            }
        }
    }
}
