CREATE TABLE ACTIVITY
(
	WORKFLOW_TYPE_ID NUMBER(18) NOT NULL
	,QUALIFIED_NAME VARCHAR2(128) NOT NULL
	,ACTIVITY_TYPE_ID NUMBER(18) NOT NULL
	,PARENT_QUALIFIED_NAME VARCHAR2(128) NULL
);

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_PK PRIMARY KEY ( WORKFLOW_TYPE_ID, QUALIFIED_NAME );

CREATE INDEX ACTIVITY_IDX01 ON ACTIVITY ( QUALIFIED_NAME );
CREATE INDEX ACTIVITY_IDX02 ON ACTIVITY ( WORKFLOW_TYPE_ID );
