CREATE TABLE ACTIVITY_STATUS_EVENT
(
	ACTIVITY_STATUS_EVENT_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,ACTIVITY_INSTANCE_ID NUMBER(18) NOT NULL
	,ACTIVITY_STATUS_ID NUMBER(4) NOT NULL
	,EVENT_ORDER NUMBER(9) NOT NULL
	,EVENT_DATE_TIME DATE NOT NULL
	,DB_EVENT_DATE_TIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
);

ALTER TABLE ACTIVITY_STATUS_EVENT ADD CONSTRAINT ACTIVITY_STATUS_EVENT_PK PRIMARY KEY ( ACTIVITY_STATUS_EVENT_ID );

CREATE INDEX ACTIVITY_STATUS_EVENT_IDX01 ON ACTIVITY_STATUS_EVENT (WORKFLOW_INSTANCE_ID);

CREATE OR REPLACE TRIGGER ACTIVITY_STATUS_EVENT_ID_TRG
BEFORE INSERT ON ACTIVITY_STATUS_EVENT
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  SELECT
    ACTIVITY_STATUS_EVENT_ID_SEQ.NEXTVAL
  INTO
    :NEW.ACTIVITY_STATUS_EVENT_ID
  FROM DUAL;
END;
/