CREATE TABLE ADDED_ACTIVITY
(
	WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_EVENT_ID NUMBER(18) NOT NULL
	,QUALIFIED_NAME VARCHAR2(128) NOT NULL
	,ACTIVITY_TYPE_ID NUMBER(18) NOT NULL
	,PARENT_QUALIFIED_NAME VARCHAR2(128) NULL
	,ADDED_ACTIVITY_ACTION VARCHAR2(2000) NULL
	,"ORDER" NUMBER(9) NULL
);

CREATE INDEX ADDED_ACTIVITY_IDX01 ON ADDED_ACTIVITY ( WORKFLOW_INSTANCE_ID );
CREATE INDEX ADDED_ACTIVITY_IDX02 ON ADDED_ACTIVITY ( WORKFLOW_INSTANCE_EVENT_ID );
CREATE INDEX ADDED_ACTIVITY_IDX03 ON ADDED_ACTIVITY ( QUALIFIED_NAME );