CREATE TABLE EVENT_ANNOTATION
(
	WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,EVENT_ID NUMBER(18) NOT NULL
	,EVENT_TYPE CHAR(1) NOT NULL
	,ANNOTATION VARCHAR2(1024) NOT NULL
);

ALTER TABLE EVENT_ANNOTATION ADD CONSTRAINT EVENT_ANNOTATION_CHK01 CHECK (EVENT_TYPE IN ('A', 'U', 'W'));

CREATE INDEX EVENT_ANNOTATION_IDX01 ON EVENT_ANNOTATION ( WORKFLOW_INSTANCE_ID );
CREATE INDEX EVENT_ANNOTATION_IDX02 ON EVENT_ANNOTATION ( EVENT_ID, EVENT_TYPE );