CREATE TABLE TRACKING_DATA_ITEM_ANNOTATION
(
	TRACKING_DATA_ITEM_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,ANNOTATION VARCHAR2(1024) NOT NULL
);

CREATE INDEX TRACKING_DATA_ANNOTATION_IDX01 ON TRACKING_DATA_ITEM_ANNOTATION ( WORKFLOW_INSTANCE_ID );
CREATE INDEX TRACKING_DATA_ANNOTATION_IDX02 ON TRACKING_DATA_ITEM_ANNOTATION ( TRACKING_DATA_ITEM_ID );