CREATE TABLE TRACKING_PROFILE_INSTANCE
(
	INSTANCE_ID CHAR(36) NOT NULL
	,TRACKING_PROFILE_XML NCLOB NULL
	,UPDATED_DATE_TIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
);

ALTER TABLE TRACKING_PROFILE_INSTANCE ADD CONSTRAINT TRACKING_PROFILE_INSTANCE_PK PRIMARY KEY ( INSTANCE_ID );

CREATE OR REPLACE TRIGGER TRACKING_PROFILE_INST_UPD_TRG
BEFORE UPDATE ON TRACKING_PROFILE_INSTANCE
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
	SELECT
		SYS_EXTRACT_UTC(SYSTIMESTAMP)
	INTO
		:NEW.UPDATED_DATE_TIME
	FROM
		DUAL;
END;
/