CREATE TABLE TYPE
(
	TYPE_ID NUMBER(18) NOT NULL
	,TYPE_FULL_NAME VARCHAR2(128) NOT NULL
	,ASSEMBLY_FULL_NAME VARCHAR2(256) NOT NULL
	,IS_INSTANCE_TYPE NUMBER(1) NOT NULL
);

ALTER TABLE TYPE ADD CONSTRAINT TYPE_PK PRIMARY KEY ( TYPE_ID );

ALTER TABLE TYPE ADD CONSTRAINT TYPE_CHK01 CHECK (IS_INSTANCE_TYPE IN (0, 1));

CREATE UNIQUE INDEX TYPE_UQ01 ON TYPE ( TYPE_FULL_NAME, ASSEMBLY_FULL_NAME );

CREATE OR REPLACE TRIGGER TYPE_ID_TRG
BEFORE INSERT ON TYPE
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  SELECT
    TYPE_ID_SEQ.NEXTVAL
  INTO
    :NEW.TYPE_ID
  FROM DUAL;
END;
/