CREATE TABLE USER_EVENT
(
	USER_EVENT_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,ACTIVITY_INSTANCE_ID NUMBER(18) NOT NULL
	,EVENT_ORDER NUMBER(9) NOT NULL
	,EVENT_DATE_TIME DATE NOT NULL
	,DB_EVENT_DATE_TIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
	,USER_DATA_KEY VARCHAR2(512) NULL
	,USER_DATA_TYPE_ID NUMBER(18) NULL
	,USER_DATA_STR NCLOB NULL
	,USER_DATA_BLOB BLOB NULL
	,USER_DATA_NON_SERIALISABLE NUMBER(1) NOT NULL
);


ALTER TABLE USER_EVENT ADD CONSTRAINT USER_EVENT_PK PRIMARY KEY ( USER_EVENT_ID );

ALTER TABLE USER_EVENT ADD CONSTRAINT USER_EVENT_CHK01 CHECK (USER_DATA_NON_SERIALISABLE IN (0, 1));

CREATE INDEX USER_EVENT_IDX01 ON USER_EVENT ( WORKFLOW_INSTANCE_ID );

CREATE OR REPLACE TRIGGER USER_EVENT_ID_TRG
BEFORE INSERT ON USER_EVENT
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  SELECT
    USER_EVENT_ID_SEQ.NEXTVAL
  INTO
    :NEW.USER_EVENT_ID
  FROM DUAL;
END;
/
