CREATE TABLE WORKFLOW_INSTANCE_EVENT
(
	WORKFLOW_INSTANCE_EVENT_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_ID NUMBER(18) NOT NULL
	,WORKFLOW_INSTANCE_STATUS_ID NUMBER(4) NOT NULL
	,EVENT_ORDER NUMBER(9) NOT NULL
	,EVENT_ARG_TYPE_ID NUMBER(18) NULL
	,EVENT_ARG BLOB NULL
	,EVENT_DATE_TIME DATE NOT NULL
	,DB_EVENT_DATE_TIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
);

ALTER TABLE WORKFLOW_INSTANCE_EVENT ADD CONSTRAINT WORKFLOW_INSTANCE_EVENT_PK PRIMARY KEY ( WORKFLOW_INSTANCE_EVENT_ID );

CREATE INDEX WORKFLOW_INSTANCE_EVENT_IDX01 ON WORKFLOW_INSTANCE_EVENT (WORKFLOW_INSTANCE_ID);

CREATE OR REPLACE TRIGGER WORKFLOW_INSTANCE_EVENT_ID_TRG
BEFORE INSERT ON WORKFLOW_INSTANCE_EVENT
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  SELECT
    WORKFLOW_INSTANCE_EVENT_ID_SEQ.NEXTVAL
  INTO
    :NEW.WORKFLOW_INSTANCE_EVENT_ID
  FROM DUAL;
END;
/