CREATE TABLE COMPLETED_SCOPE
(
	INSTANCE_ID CHAR(36) NOT NULL
	,COMPLETED_SCOPE_ID CHAR(36) NOT NULL
	,STATE BLOB NOT NULL
	,MODIFIED DATE NOT NULL
);

ALTER TABLE COMPLETED_SCOPE ADD CONSTRAINT COMPLETED_SCOPE_PK PRIMARY KEY ( COMPLETED_SCOPE_ID );

CREATE INDEX COMPLETED_SCOPE_IDX01 ON COMPLETED_SCOPE ( INSTANCE_ID );