DELIMITER $$

DROP PROCEDURE IF EXISTS DeleteTrackingProfile $$
/*
 * Remove a tracking profile for a workflow type
 */
CREATE PROCEDURE DeleteTrackingProfile
(
	IN p_TYPE_FULL_NAME VARCHAR(128)
	,IN p_ASSEMBLY_FULL_NAME VARCHAR(256)
)
BEGIN
	DECLARE l_TYPE_ID BIGINT UNSIGNED;
	
	CALL GetTypeId(l_TYPE_ID, p_TYPE_FULL_NAME, p_ASSEMBLY_FULL_NAME, NULL);

	INSERT INTO TRACKING_PROFILE
	(
		VERSION
		,WORKFLOW_TYPE_ID
		,TRACKING_PROFILE_XML
		,INSERT_DATE_TIME
	)
	VALUES
	(
		'-1'
		,l_TYPE_ID
		,NULL
		,UTC_TIMESTAMP()
	);
	
END $$

DELIMITER ;
