DELIMITER $$

DROP PROCEDURE IF EXISTS InsertEventAnnotation $$
/*
 * Insert a single event annotation.
 */	
CREATE PROCEDURE InsertEventAnnotation
(
	IN p_WORKFLOW_INSTANCE_ID BIGINT UNSIGNED
	,IN p_EVENT_ID BIGINT UNSIGNED
	,IN p_EVENT_TYPE CHAR(1)
	,IN p_ANNOTATION VARCHAR(1024)
)
sproc:BEGIN

	INSERT INTO EVENT_ANNOTATION
	(
		WORKFLOW_INSTANCE_ID
		,EVENT_ID
		,EVENT_TYPE
		,ANNOTATION
	)
	VALUES
	(
		p_WORKFLOW_INSTANCE_ID
		,p_EVENT_ID
		,p_EVENT_TYPE
		,p_ANNOTATION
	);
	
END $$

DELIMITER ;
