DELIMITER $$

DROP PROCEDURE IF EXISTS InsertUserTrackingRecord $$
/*
 * Insert a single user tracking record.
 */	
CREATE PROCEDURE InsertUserTrackingRecord
(
	IN p_WORKFLOW_INSTANCE_ID BIGINT UNSIGNED
	,INOUT p_ACTIVITY_INSTANCE_ID BIGINT UNSIGNED
	,IN p_QUALIFIED_NAME VARCHAR(128)
	,IN p_CONTEXT_GUID CHAR(36)
	,IN p_PARENT_CONTEXT_GUID CHAR(36)
	,IN p_EVENT_DATE_TIME DATETIME
	,IN p_EVENT_ORDER INT UNSIGNED
	,IN p_USER_DATA_KEY VARCHAR(512)
	,IN p_USER_DATA_TYPE_NAME VARCHAR(128)
	,IN p_USER_DATA_ASSEMBLY_NAME VARCHAR(256)
	,IN p_USER_DATA_STR LONGTEXT
	,IN p_USER_DATA_BLOB BLOB
	,IN p_USER_DATA_NON_SERIALISABLE BOOLEAN
	,OUT p_USER_EVENT_ID BIGINT UNSIGNED
)
BEGIN
	DECLARE l_USER_DATA_TYPE_ID BIGINT UNSIGNED;
	
	IF p_ACTIVITY_INSTANCE_ID IS NULL THEN
		-- grab the activity instance id
		CALL GetActivityInstanceId(p_WORKFLOW_INSTANCE_ID, 
			p_QUALIFIED_NAME, p_CONTEXT_GUID, p_PARENT_CONTEXT_GUID, 
			p_ACTIVITY_INSTANCE_ID);
	END IF;
	
	CALL GetTypeId(l_USER_DATA_TYPE_ID, p_USER_DATA_TYPE_NAME, p_USER_DATA_ASSEMBLY_NAME, NULL);
	
	-- and insert the actual record into the event table
	INSERT INTO USER_EVENT
	(
		WORKFLOW_INSTANCE_ID
		,ACTIVITY_INSTANCE_ID
		,EVENT_ORDER
		,EVENT_DATE_TIME
		,DB_EVENT_DATE_TIME
		,USER_DATA_KEY
		,USER_DATA_TYPE_ID
		,USER_DATA_STR
		,USER_DATA_BLOB
		,USER_DATA_NON_SERIALISABLE
	)
	VALUES
	(
		p_WORKFLOW_INSTANCE_ID
		,p_ACTIVITY_INSTANCE_ID
		,p_EVENT_ORDER
		,p_EVENT_DATE_TIME
		,UTC_TIMESTAMP()
		,p_USER_DATA_KEY
		,l_USER_DATA_TYPE_ID
		,p_USER_DATA_STR
		,p_USER_DATA_BLOB
		,p_USER_DATA_NON_SERIALISABLE
	);
	
	SET p_USER_EVENT_ID = LAST_INSERT_ID();
END $$

DELIMITER ;
