DELIMITER $$

DROP PROCEDURE IF EXISTS InsertTrackingDataItem $$
/*
 * Insert a single tracking data item
 */	
CREATE PROCEDURE InsertTrackingDataItem
(
	IN p_WORKFLOW_INSTANCE_ID BIGINT UNSIGNED
	,IN p_EVENT_ID BIGINT UNSIGNED
	,IN p_EVENT_TYPE CHAR(1)
	,IN p_FIELD_NAME VARCHAR(256)
	,IN p_TYPE_FULL_NAME VARCHAR(128)
	,IN p_ASSEMBLY_FULL_NAME VARCHAR(256)
	,IN p_DATA_STR LONGTEXT
	,IN p_DATA_BLOB BLOB
	,IN p_DATA_NON_SERIALISABLE BOOLEAN
	,OUT p_TRACKING_DATA_ITEM_ID BIGINT UNSIGNED
)
sproc:BEGIN
	DECLARE l_FIELD_TYPE_ID BIGINT UNSIGNED;
	
	CALL GetTypeId(l_FIELD_TYPE_ID, p_TYPE_FULL_NAME, p_ASSEMBLY_FULL_NAME, NULL);
	
	INSERT INTO TRACKING_DATA_ITEM
	(
		WORKFLOW_INSTANCE_ID
		,EVENT_ID
		,EVENT_TYPE
		,FIELD_NAME
		,FIELD_TYPE_ID
		,DATA_STR
		,DATA_BLOB
		,DATA_NON_SERIALISABLE
	)
	VALUES
	(
		p_WORKFLOW_INSTANCE_ID
		,p_EVENT_ID
		,p_EVENT_TYPE
		,p_FIELD_NAME
		,l_FIELD_TYPE_ID
		,p_DATA_STR
		,p_DATA_BLOB
		,p_DATA_NON_SERIALISABLE
	);
	
	SET p_TRACKING_DATA_ITEM_ID = LAST_INSERT_ID();
	
END $$

DELIMITER ;
