DELIMITER $$

DROP PROCEDURE IF EXISTS InsertWorkflow $$
/*
 * Insert a workflow type record.
 */
CREATE PROCEDURE InsertWorkflow
(
	IN p_TYPE_FULL_NAME VARCHAR(128)
	,IN p_ASSEMBLY_FULL_NAME VARCHAR(256)
	,IN p_IS_INSTANCE_TYPE BOOLEAN
	,IN p_WORKFLOW_DEFINITION LONGTEXT
	,OUT p_WORKFLOW_TYPE_ID BIGINT UNSIGNED
	,OUT p_EXISTS BOOLEAN
)
BEGIN
	CALL GetTypeId(p_WORKFLOW_TYPE_ID, p_TYPE_FULL_NAME, p_ASSEMBLY_FULL_NAME, p_IS_INSTANCE_TYPE);
	
	IF NOT EXISTS (SELECT NULL FROM WORKFLOW WHERE WORKFLOW_TYPE_ID = p_WORKFLOW_TYPE_ID) THEN
		SET p_EXISTS = FALSE;
		INSERT INTO WORKFLOW
		(
			WORKFLOW_TYPE_ID
			,WORKFLOW_DEFINITION
		)
		VALUES
		(
			p_WORKFLOW_TYPE_ID
			,p_WORKFLOW_DEFINITION
		);
	ELSE
		SET p_EXISTS = TRUE;
	END IF;
END $$

DELIMITER ;
