DELIMITER $$

DROP PROCEDURE IF EXISTS UpdateTrackingProfile $$
/*
 * Create a new version of the tracking profile for a particular workflow type
 */
CREATE PROCEDURE UpdateTrackingProfile
(
	IN p_TYPE_FULL_NAME VARCHAR(128)
	,IN p_ASSEMBLY_FULL_NAME VARCHAR(256)
	,IN p_VERSION VARCHAR(32)
	,IN p_TRACKING_PROFILE_XML LONGTEXT
)
BEGIN
	DECLARE l_TYPE_ID BIGINT UNSIGNED;
	
	CALL GetTypeId(l_TYPE_ID, p_TYPE_FULL_NAME, p_ASSEMBLY_FULL_NAME, NULL);
	
	INSERT INTO TRACKING_PROFILE
	(
		VERSION
		,WORKFLOW_TYPE_ID
		,TRACKING_PROFILE_XML
		,INSERT_DATE_TIME
	)
	VALUES
	(
		p_VERSION
		,l_TYPE_ID
		,p_TRACKING_PROFILE_XML
		,UTC_TIMESTAMP()
	);
END $$

DELIMITER ;
