DELIMITER $$

DROP PROCEDURE IF EXISTS RetrieveCompletedScope $$
CREATE PROCEDURE RetrieveCompletedScope
(
  IN p_COMPLETED_SCOPE_ID CHAR(36)
  ,OUT p_RESULT INTEGER
)
BEGIN
    SELECT
      STATE
    FROM
      COMPLETED_SCOPE
    WHERE
      COMPLETED_SCOPE_ID = p_COMPLETED_SCOPE_ID;

    SET p_RESULT = ROW_COUNT();
END $$

DELIMITER ;
