DELIMITER $$

DROP PROCEDURE IF EXISTS UnlockInstanceState $$
CREATE PROCEDURE UnlockInstanceState
(
  IN p_INSTANCE_ID CHAR(36)
  ,IN p_OWNER_ID CHAR(36)
)
BEGIN
  UPDATE INSTANCE_STATE
  SET
    OWNER_ID = NULL
    ,OWNED_UNTIL = NULL
  WHERE
    INSTANCE_ID = p_INSTANCE_ID
    AND (
      (OWNER_ID = p_OWNER_ID AND OWNED_UNTIL < UTC_TIMESTAMP())
      OR
      (OWNER_ID IS NULL AND OWNED_UNTIL IS NULL)
    );

END $$

DELIMITER ;
