DROP TABLE IF EXISTS ACTIVITY_STATUS_EVENT;
CREATE TABLE ACTIVITY_STATUS_EVENT
(
	ACTIVITY_STATUS_EVENT_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL
	,WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,EVENT_ORDER INT UNSIGNED NOT NULL
	,ACTIVITY_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,ACTIVITY_STATUS_ID SMALLINT UNSIGNED NOT NULL
	,EVENT_DATE_TIME DATETIME NOT NULL
	,DB_EVENT_DATE_TIME DATETIME NOT NULL
	,PRIMARY KEY ( ACTIVITY_STATUS_EVENT_ID )
);

CREATE INDEX ACTIVITY_STATUS_EVENT_IDX01 ON ACTIVITY_STATUS_EVENT (WORKFLOW_INSTANCE_ID);