DROP TABLE IF EXISTS EVENT_ANNOTATION;
CREATE TABLE EVENT_ANNOTATION
(
	WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,EVENT_ID BIGINT UNSIGNED NOT NULL
	,EVENT_TYPE CHAR(1) NOT NULL
	,ANNOTATION VARCHAR(1024) NOT NULL
);

CREATE INDEX EVENT_ANNOTATION_IDX01 ON EVENT_ANNOTATION ( WORKFLOW_INSTANCE_ID );
CREATE INDEX EVENT_ANNOTATION_IDX02 ON EVENT_ANNOTATION ( EVENT_ID, EVENT_TYPE );