DROP TABLE IF EXISTS REMOVED_ACTIVITY;
CREATE TABLE REMOVED_ACTIVITY
(
	WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,WORKFLOW_INSTANCE_EVENT_ID BIGINT UNSIGNED NOT NULL
	,QUALIFIED_NAME VARCHAR(128) NOT NULL
	,ACTIVITY_TYPE_ID BIGINT UNSIGNED NOT NULL
	,PARENT_QUALIFIED_NAME VARCHAR(128) NULL
	,REMOVED_ACTIVITY_ACTION VARCHAR(2000) NULL
	,`ORDER` INT UNSIGNED NULL
);

CREATE INDEX REMOVED_ACTIVITY_IDX01 ON REMOVED_ACTIVITY ( WORKFLOW_INSTANCE_ID );
CREATE INDEX REMOVED_ACTIVITY_IDX02 ON REMOVED_ACTIVITY ( WORKFLOW_INSTANCE_EVENT_ID );
CREATE INDEX REMOVED_ACTIVITY_IDX03 ON REMOVED_ACTIVITY( QUALIFIED_NAME );