DROP TABLE IF EXISTS TRACKING_DATA_ITEM;
CREATE TABLE TRACKING_DATA_ITEM 
(
	TRACKING_DATA_ITEM_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL
	,WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,EVENT_ID BIGINT UNSIGNED NOT NULL
	,EVENT_TYPE CHAR(1) NOT NULL
	,FIELD_NAME VARCHAR(256) NOT NULL
	,FIELD_TYPE_ID BIGINT UNSIGNED NOT NULL
	,DATA_STR LONGTEXT NULL
	,DATA_BLOB BLOB NULL
	,DATA_NON_SERIALISABLE BOOLEAN NOT NULL
	,PRIMARY KEY ( TRACKING_DATA_ITEM_ID )
);

CREATE INDEX TRACKING_DATA_ITEM_IDX01 ON TRACKING_DATA_ITEM ( WORKFLOW_INSTANCE_ID, EVENT_ID, EVENT_TYPE );