DROP TABLE IF EXISTS TRACKING_PROFILE_INSTANCE;
CREATE TABLE TRACKING_PROFILE_INSTANCE
(
	INSTANCE_ID CHAR(36) NOT NULL
	,TRACKING_PROFILE_XML LONGTEXT NULL
	,UPDATED_DATE_TIME DATETIME NOT NULL
	,PRIMARY KEY ( INSTANCE_ID )
);
