DROP TABLE IF EXISTS TRACKING_DATA_ITEM_ANNOTATION;
CREATE TABLE TRACKING_DATA_ITEM_ANNOTATION
(
	TRACKING_DATA_ITEM_ID BIGINT UNSIGNED NOT NULL
	,WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,ANNOTATION VARCHAR(1024) NOT NULL
);

CREATE INDEX TRACKING_DATA_ANNOTATION_IDX01 ON TRACKING_DATA_ITEM_ANNOTATION ( WORKFLOW_INSTANCE_ID );
CREATE INDEX TRACKING_DATA_ANNOTATION_IDX02 ON TRACKING_DATA_ITEM_ANNOTATION ( TRACKING_DATA_ITEM_ID );