DROP TABLE IF EXISTS TRACKING_PROFILE;
CREATE TABLE TRACKING_PROFILE
(
	TRACKING_PROFILE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL
	,VERSION VARCHAR(32) NOT NULL
	,WORKFLOW_TYPE_ID BIGINT UNSIGNED NOT NULL
	,TRACKING_PROFILE_XML LONGTEXT NULL
	,INSERT_DATE_TIME DATETIME NOT NULL
	,PRIMARY KEY ( TRACKING_PROFILE_ID )
);

CREATE INDEX TRACKING_PROFILE_IDX01 ON TRACKING_PROFILE ( WORKFLOW_TYPE_ID, VERSION, INSERT_DATE_TIME );