DROP TABLE IF EXISTS TYPE;
CREATE TABLE TYPE
(
	TYPE_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL
	,TYPE_FULL_NAME VARCHAR(128) NOT NULL
	,ASSEMBLY_FULL_NAME VARCHAR(256) NOT NULL
	,IS_INSTANCE_TYPE BOOLEAN NOT NULL
	,PRIMARY KEY ( TYPE_ID )
);

CREATE UNIQUE INDEX TYPE_UQ01 ON TYPE ( TYPE_FULL_NAME, ASSEMBLY_FULL_NAME );
