DROP TABLE IF EXISTS USER_EVENT;
CREATE TABLE USER_EVENT
(
	USER_EVENT_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL
	,WORKFLOW_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,ACTIVITY_INSTANCE_ID BIGINT UNSIGNED NOT NULL
	,EVENT_ORDER INT UNSIGNED NOT NULL
	,EVENT_DATE_TIME DATETIME NOT NULL
	,DB_EVENT_DATE_TIME DATETIME NOT NULL
	,USER_DATA_KEY VARCHAR(512) NULL
	,USER_DATA_TYPE_ID BIGINT UNSIGNED NULL
	,USER_DATA_STR LONGTEXT NULL
	,USER_DATA_BLOB BLOB NULL
	,USER_DATA_NON_SERIALISABLE BOOLEAN NOT NULL
	,PRIMARY KEY ( USER_EVENT_ID )
);

CREATE INDEX USER_EVENT_IDX01 ON USER_EVENT ( WORKFLOW_INSTANCE_ID );